<?php
  include( "account/cookie.php" );
  require_once __DIR__ . '/../filemaker/data-api.php';
  // get user record
  // echo $uID;
  $request = array(
    'database' => 'MCH-Navigator',
    'layout' => 'MCH_Smart_Dashboard',
    'action' => 'single',
    'record' => (int) $uID,
  );

  $result = do_filemaker_request($request, 'array');
  $recordData = $result['response']['data'][0] ?? array(
    'recordId' => (int) $uID,
    'fieldData' => array(),
  );
  $record = fm_record_shim($recordData);

  // print_r($record);


  $section = 'assessment';
  $page = 'Course Dashboard';
  include( 'incl/header.html' )
  ?>
<div class="container wrapper">
	<?php include('incl/nav_generic.html') ?>
	<div class="ten columns">
		<div id="page_title">
			<img src="images/Dashboard-lightbulb-concept.jpg" alt="lightbulb and paper with pencil">
			<div class="v">
				<h1>Course Dashboard</h1>
			</div>
		</div>


		<?php
      if( empty($record->getField('name_first')) ){
        echo '<h2>Welcome ' . $record->getField('email'). ' <small><a href="/smart/account/edit.php">Finish Your Profile</a></small></h2>';
      } else {
        echo '<h2>Welcome ' . $record->getField('name_first'). '</h2>';
      }
    ?>


		<?php if(isset($_GET["saved"])){ ?>
		<p class="saved">Your responses for Competency <?php echo $_GET["saved"]; ?> have been saved!<br>
			You can take additional competencies or see your Personalized Learning Plan below.
		</p>
		<?php } ?>
		<p>MCHsmart delivers the core content needed to move MCH knowledge to action in a format that is accessible to MCH professionals in field-based settings, current and future faculty, and students at all levels. The curriculum is organized around the MCH Leadership Competencies. (In case you missed the video introduction to the MCH Leadership Competencies, <a href="https://www.mchnavigator.org/smart/video.php">you can view it here</a>).</p>
		<p><strong>How to Use. </strong>The course allows you to work at your own pace and choose how deeply you want to explore the knowledge areas and skills for each competency. Each module takes approximately 1 hour to complete (12 hours for the entire course). See the graphic and description below to learn about the <strong>three-step process</strong>. <strong>Return to this Dashboard at any point in the course (through the navigation at the top or left of the page) to check your progress; scroll down for all the components of the curriculum. </strong></p>
		<!-- <h2>Scroll down to access resources for each step.</h2> -->
		<p>&nbsp;</p>
		<!-- <p><img src="../images/MCHsmart-flow-2.png" width="1157" height="418" usemap="#powerpuffgirls" /></p> -->
		<!-- Image Map Generated by http://www.image-map.net/ -->
		<img src="../images/MCHsmart-flow-3.png" alt="This image visually outlines the process explained in the text below" usemap="#steps">
		<p><strong>What You Need to Complete the Course.</strong> There are many components of this online curriculum.  Remember that <strong><em>you are able to proceed through the content as deeply or as quickly as you would like</em></strong><em>,</em> based on your needs and learning interests. However, there are some requirements to receive your certificate.</p>
		<p>To make your journey easier, here is a <strong><em>summary of everything that you need to complete the course</em></strong>. Use the links below in this dashboard to access each course component.</p>
		<ul>
			<li><strong>Pre-Test.</strong> Use this to gain a baseline of your knowledge.</li>
			<li><strong>Modules.</strong> Each of the 12 modules consists of three pages (micro-, meso-, and macro-learning). <strong><em>At the end of each page, you are required to fill out two questions related to your knowledge and skills.</em></strong> You can dive as deeply into the content on each page.</li>
			<li><strong>Post-Test.</strong> Use this to gauge how much you have learned. You need a score of 80% to proceed.</li>
			<li><strong>Provide Feedback.</strong> Your feedback will help us improve the course (optional).</li>
			<li><strong>Print the Certificate.</strong> Congratulations! Thanks for taking the course and <a href="mailto:jrichard@ncemch.org">contact us</a> if you have any difficulties along the way.</li>
		</ul>
		<map name="steps">
			<area target="" alt="1: Reflect" href="#self-reflection" coords="353,552,345" shape="circle">
			<area target="" alt="2: Learn" href="#learning" coords="1230,553,433" shape="circle">
			<area target="" alt="3: Share" href="#sharing" coords="2087,554,348" shape="circle">
			<area target="" alt="Certificate of Completion" href="#coc" coords="2452,421,2736,796" shape="rect">
		</map>


		<section class="evidenceBorder blue" id="self-reflection">
			<header>
				<i class="mch-light-bulb"></i>
				<h2>STEP 1: REFLECT</h2>
				<p>Find your starting point and set goals for learning.</p>
			</header>

			<p><strong>1A. Get Ready. </strong>Think about what you already know about the MCH Leadership Competencies and the skills and knowledge they describe.</p>
			<p>Consider the following:
			<ul>
				<li>Which competencies are you most eager to learn about?</li>
				<li>Which will help you the most in your daily work?</li>
				<li>Which are you already familiar with?</li>
			</ul>
			<p><strong>1B. Find Your Baseline (Pre-Test). </strong><?php if($record->getField('Smart_Pretest_Score') == ''){ ?>Now, take the pre-test to document your knowledge and skill level.<?php } ?></p>

			<?php if($record->getField('Smart_Pretest_Score') == ''){ ?><p><a href="test/pre.php" class="button">TAKE THE PRE-TEST</a></p><?php } ?>

			<?php if($record->getField('Smart_Pretest_Score') != ''){ ?>
			<aside class="attention">
				<h2><i class="mch-check-square-o"></i> Pre-Test Complete</h2>
				<p>Score: <?php echo $record->getField('Smart_Pretest_Score'); ?>% <a href="test/review.php?type=pre" class="pad-left">View Pre-Test Responses</a> <a href="test/pre.php" class="pad-left">Retake Pre-Test</a></p>
			</aside>
			<?php } ?>
			<p><strong>1C. Get Started. </strong>Set your intention to learn, then move on to the next step.</p>
			<?php
        $all_modules_complete = "true";
        $modules_completed = 0;
        function module_status($m) {
          global $record, $all_modules_complete, $modules_completed;
          if( $record->getField('MCH_Smart_Baseline::Competency_'.$m.'_Status') == "Complete" ) {
            echo '<img src="/smart/images/complete.gif" class="status">';
            $modules_completed++;
          } else if( $record->getField('MCH_Smart_Baseline::Competency_'.$m.'_Status') == "Incomplete" ) {
            echo '<img src="/smart/images/incomplete.gif" class="status">';
            $all_modules_complete = "false";
          } else {
            echo '<img src="/smart/images/not-started.gif" class="status">';
            $all_modules_complete = "false";
          }
        }
        ?>
		</section>


		<style type="text/css">
		.red h2,
		.red h3 {
			color: #e82e5d;
		}

		.green h2,
		.green h3 {
			color: #5d9e21;
		}

		.module {
			padding: 1rem;
			margin-bottom: 2rem;
			border: 1px solid lightgrey;
			box-shadow: 0 5px 5px 0 rgb(0 0 0 / 5%);
			border-radius: 10px;
		}

		.module ul {
			padding: 0;
			margin: 0;
			list-style: none;
		}

		.module ul li:before {
			content: none;
		}

		.attention {
			padding: 2rem 1rem 1rem;
			margin-bottom: 2rem;
			background-color: #f2f2f2;
			border-radius: 10px;
			text-align: center;
		}

		.evidenceBorder.blue {
			border: solid 4px #237bbf;
		}

		.evidenceBorder.red {
			border: solid 4px #e82e5d;
		}

		.evidenceBorder.green {
			border: solid 4px #5d9e21;
		}

		.evidenceBorder.coc {
			border: solid 4px #fbb03b;
		}

		section.evidenceBorder header {
			position: relative;
			color: white;
			text-align: center;
			width: calc(100% + 4rem);
			margin: -2rem 0 2rem -2rem;
			padding: 1rem 0;
			border: none;
		}

		section.evidenceBorder.blue header {
			background-color: #237bbf;
		}

		section.evidenceBorder.red header {
			background-color: #e82e5d;
		}

		section.evidenceBorder.green header {
			background-color: #5d9e21;
		}

		section.evidenceBorder.coc header {
			background-color: #fbb03b;
		}

		section.evidenceBorder header i {
			/*color: white;*/
			font-size: 7rem;
			position: absolute;
			opacity: .25;
			top: -11px;
			margin-left: -60px;
		}

		section.evidenceBorder header h2 {
			color: white;
			font-size: 2rem;
		}

		section.evidenceBorder header p {
			/*color: white;*/
			font-size: 1rem;
		}

		html {
			scroll-behavior: smooth;
		}

		.pad-left {
			margin-left: 2rem;
		}

		.alert {
			padding: 4px 8px;
			border: solid 1px red;
			color: red;
			background-color: #ffe2e2;
			border-radius: 10px;
		}

		</style>


		<section class="evidenceBorder red" id="learning">
			<header>
				<i class="mch-book-open"></i>
				<h2>STEP 2: LEARN</h2>
				<p>Take a deep dive into each competency and its knowledge and skill areas.</p>
			</header>

			<p><strong>2A. Map Out Your Learning. </strong>Your learning journey is unique to your interests and needs. Explore the curriculum as deeply as you&rsquo;d like:
			<ul>
				<li>Get a quick overview of a competency by watching the video introduction in the <strong>Micro-Learning</strong> section (page 1 of each module).</li>
				<li>Take a deeper dive and delve into the lessons and professional literature presented in the <strong>Meso-Learning</strong> section (page 2 of each module).</li>
				<li>Understand how to implement each competency by exploring the curated collections of trainings in the <strong>Macro-Learning </strong>section (page 3 of each module).</li>
			</ul>
			<p><strong>2B. Engage in Active Learning. </strong>You can complete each module sequentially, or pick and choose what you&rsquo;d like to work on through the links on this page.</p>
			<p><strong>2C. Track Your Learning. </strong>You will be asked to respond to two questions at the end of each module page. When you answer each set of self-evaluation questions, click the “save” button to let us know you're done with that section. In the list below, you’ll see a green checkmark appear next to each section you have completed. <em><strong>Don't forget to save your responses!</strong></em></p>


			<div class="charts-container">

				<div class="pie-wrapper progress donut">
					<span class="label" id="modules_completed">?/36</span>
					<div class="pie">
						<div class="left-side half-circle"></div>
						<div class="right-side half-circle"></div>
					</div>
					<div class="unfinished"></div>
				</div>

			</div>


			<h3>Self</h3>

			<div class="row">
				<div class="module six columns">
					<h4>1. MCH Knowledge Base/Context</h4>
					<ul>
						<li>
							<?php module_status('1_1'); ?>
							<a href="/smart/1-mch-knowledge/1-1-micro-learning.php">1.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('1_2'); ?>
							<a href="/smart/1-mch-knowledge/1-2-meso-learning.php">1.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('1_3'); ?>
							<a href="/smart/1-mch-knowledge/1-3-macro-learning.php">1.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
				<div class="module six columns">
					<h4>2. Self Reflection</h4>
					<ul>
						<li>
							<?php module_status('2_1'); ?>
							<a href="/smart/2-self-reflection/2-1-micro-learning.php">2.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('2_2'); ?>
							<a href="/smart/2-self-reflection/2-2-meso-learning.php">2.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('2_3'); ?>
							<a href="/smart/2-self-reflection/2-3-macro-learning.php">2.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="module six columns">
					<h4>3. Ethics</h4>
					<ul>
						<li>
							<?php module_status('3_1'); ?>
							<a href="/smart/3-ethics/3-1-micro-learning.php">3.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('3_2'); ?>
							<a href="/smart/3-ethics/3-2-meso-learning.php">3.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('3_3'); ?>
							<a href="/smart/3-ethics/3-3-macro-learning.php">3.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
				<div class="module six columns">
					<h4>4. Critical Thinking</h4>
					<ul>
						<li>
							<?php module_status('4_1'); ?>
							<a href="/smart/4-critical-thinking/4-1-micro-learning.php">4.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('4_2'); ?>
							<a href="/smart/4-critical-thinking/4-2-meso-learning.php">4.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('4_3'); ?>
							<a href="/smart/4-critical-thinking/4-3-macro-learning.php">4.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
			</div>


			<h3>Others</h3>
			<div class="row">
				<div class="module six columns">
					<h4>5. Communication</h4>
					<ul>
						<li>
							<?php module_status('5_1'); ?>
							<a href="/smart/5-communication/5-1-micro-learning.php">5.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('5_2'); ?>
							<a href="/smart/5-communication/5-2-meso-learning.php">5.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('5_3'); ?>
							<a href="/smart/5-communication/5-3-macro-learning.php">5.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
				<div class="module six columns">
					<h4>6. Negotiation & Conflict Resolution</h4>
					<ul>
						<li>
							<?php module_status('6_1'); ?>
							<a href="/smart/6-negotiation-conflict-resolution/6-1-micro-learning.php">6.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('6_2'); ?>
							<a href="/smart/6-negotiation-conflict-resolution/6-2-meso-learning.php">6.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('6_3'); ?>
							<a href="/smart/6-negotiation-conflict-resolution/6-3-macro-learning.php">6.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="module six columns">
					<h4>7. Creating Responsive and Effective MCH Systems</h4>
					<ul>
						<li>
							<?php module_status('7_1'); ?>
							<a href="/smart/7-responsive-mch-systems/7-1-micro-learning.php">7.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('7_2'); ?>
							<a href="/smart/7-responsive-mch-systems/7-2-meso-learning.php">7.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('7_3'); ?>
							<a href="/smart/7-responsive-mch-systems/7-3-macro-learning.php">7.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
				<div class="module six columns">
					<h4>8. Community Expertise and Perspectives</h4>
					<ul>
						<li>
							<?php module_status('8_1'); ?>
							<a href="/smart/8-community-perspectives/8-1-micro-learning.php">8.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('8_2'); ?>
							<a href="/smart/8-community-perspectives/8-2-meso-learning.php">8.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('8_3'); ?>
							<a href="/smart/8-community-perspectives/8-3-macro-learning.php">8.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="module six columns">
					<h4>9. Teaching, Coaching, and Mentoring</h4>
					<ul>
						<li>
							<?php module_status('9_1'); ?>
							<a href="/smart/9-teaching-coaching-mentoring/9-1-micro-learning.php">9.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('9_2'); ?>
							<a href="/smart/9-teaching-coaching-mentoring/9-2-meso-learning.php">9.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('9_3'); ?>
							<a href="/smart/9-teaching-coaching-mentoring/9-3-macro-learning.php">9.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
				<div class="module six columns">
					<h4>10. Interdisciplinary / Interprofessional Team Building</h4>
					<ul>
						<li>
							<?php module_status('10_1'); ?>
							<a href="/smart/10-teambuilding/10-1-micro-learning.php">10.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('10_2'); ?>
							<a href="/smart/10-teambuilding/10-2-meso-learning.php">10.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('10_3'); ?>
							<a href="/smart/10-teambuilding/10-3-macro-learning.php">10.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
			</div>
			<h3>Wider Community</h3>
			<div class="row">
				<div class="module six columns">
					<h4>11. Systems Approach</h4>
					<ul>
						<li>
							<?php module_status('11_1'); ?>
							<a href="/smart/11-systems-approach/11-1-micro-learning.php">11.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('11_2'); ?>
							<a href="/smart/11-systems-approach/11-2-meso-learning.php">11.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('11_3'); ?>
							<a href="/smart/11-systems-approach/11-3-macro-learning.php">11.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
				<div class="module six columns">
					<h4>12. Policy</h4>
					<ul>
						<li>
							<?php module_status('12_1'); ?>
							<a href="/smart/12-policy/12-1-micro-learning.php">12.1 Micro-Learning</a>
						</li>
						<li>
							<?php module_status('12_2'); ?>
							<a href="/smart/12-policy/12-2-meso-learning.php">12.2 Meso-Learning</a>
						</li>
						<li>
							<?php module_status('12_3'); ?>
							<a href="/smart/12-policy/12-3-macro-learning.php">12.3 Macro-Learning</a>
						</li>
					</ul>
				</div>
			</div>
		</section>


		<style>
		/*https://codepen.io/jo-asakura/pen/NWWrWj*/
		.charts-container *,
		.charts-container :after,
		.charts-container :before {
			box-sizing: border-box
		}

		.charts-container {
			font-size: 10em;
			/*color: #444;*/
		}

		.charts-container:after {
			clear: both;
			content: "";
			display: table
		}

		.pie-wrapper {
			height: 1em;
			width: 1em;
			/*float: left;*/
			margin: 1rem auto;
			position: relative
		}

		.pie-wrapper .pie,
		.pie-wrapper .pie .half-circle {
			height: 100%;
			width: 100%;
			clip: rect(0, 1em, 1em, .5em);
			left: 0;
			position: absolute;
			top: 0
		}

		.pie-wrapper .pie .half-circle {
			border: .1em solid #7abe69;
			border-radius: 50%;
			clip: rect(0, .5em, 1em, 0)
		}

		.pie-wrapper .label {
			border-radius: 50%;
			bottom: .4em;
			cursor: default;
			display: block;
			font-size: .25em;
			left: .4em;
			line-height: 2.8em;
			position: absolute;
			right: .4em;
			text-align: center;
			top: .6em
		}

		.pie-wrapper .label .smaller {
			color: #f2f2f2;
			font-size: .45em;
			padding-bottom: 20px;
			vertical-align: super
		}

		.pie-wrapper .unfinished {
			height: 100%;
			width: 100%;
			border: .1em solid #f2f2f2;
			border-radius: 50%
		}

		.pie-wrapper.donut .label {
			background: 0 0;
			color: #7abe69
		}

		.pie-wrapper.progress .pie .half-circle {
			border-color: #7abe69
		}

		.pie-wrapper.progress .pie .left-side {
			transform: rotate(<?php echo $modules_completed/36*100*3.6; ?>deg)
		}

		<?php if($modules_completed <=18) {
			?>.pie-wrapper.progress .pie .right-side {
				display: none;
			}

			<?php
		}

		else {
			?>.pie-wrapper.progress .pie {
				clip: rect(auto, auto, auto, auto);
			}

			.pie-wrapper.progress .pie .right-side {
				transform: rotate(180deg);
			}

			<?php
		}

		?>

		</style>


		<section class="evidenceBorder green" id="sharing">
			<header>
				<i class="mch-comments"></i>
				<h2>STEP 3: ASSESS</h2>
				<p>Test what you&rsquo;ve learned and then let us know what you think.</p>
			</header>

			<p><strong>3A. See Your Progress (Post-Test). </strong>Once you’ve set the learning intentions you set out for yourself in Step 1 and have explored the MCH Leadership Competencies in Step 2, complete the reflective post-test. Use the results to better understand how your knowledge of the concepts and ideas in the curriculum has changed.</p>


			<?php
          if($record->getField('Smart_Pretest_Score') == '' || $all_modules_complete == "false"){
            ?>
			<p class="alert">A link to the post-test will be available when the pre-test and all module check-ins have been completed.</p>
			<?php
          } else if($record->getField('Smart_Pretest_Score') != '' && $record->getField('Smart_Posttest_Score') == ''){
            ?>
			<p><a href="test/post.php" class="button">Take the Post-Test</a></p>
			<?php
          } else if ($record->getField('Smart_Pretest_Score') != '' && $record->getField('Smart_Posttest_Score') != '') {
            ?>
			<aside class="attention">
				<h2><i class="mch-check-square-o"></i> Post-Test Complete</h2>
				<p>Score: <?php echo $record->getField('Smart_Posttest_Score'); ?>% <a href="test/review.php?type=post" class="pad-left">View Post-Test Responses</a> <a href="test/post.php" class="pad-left">Retake Post-Test</a></p>
			</aside>
			<?php
          } ?>
			<!--       <p><strong>3B. Share Reflections. </strong>Share the thoughts and insights you had as you progressed through the curriculum on the MCHtalk blog.</p>
      <ul>
        <li><a href="reflections.php">Reflections Opportunity</a></li>
      </ul> -->
			<p><strong>3B. Provide Feedback. </strong>Finally, share your feedback about MCHsmart with us (optional).</p>
			<ul>
				<li><a href="feedback.php">Evaluate this Curriculum</a></li>
			</ul>
		</section>


		<section class="evidenceBorder coc" id="coc">
			<header>
				<i class="mch-trophy"></i>
				<h2>CERTIFICATE OF COMPLETION</h2>
				<p>Use this certificate to document your learning. </p>
			</header>
			<p>In order to qualify for the certificate, you must score above an 80% on the post-test and fill out the check-in questions at the bottom of each module page. Up to 12 CPH Recertification Credits from the <a href="https://www.nbphe.org/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.nbphe.org/&amp;source=gmail&amp;ust=1655394848469000&amp;usg=AOvVaw3kV06CLva4DJCFPbyz9Aii">National Board of Public Health Examiners</a> may be earned by completion of this curriculum as listed in the <a href="https://activityfinder.nbphe.org/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://activityfinder.nbphe.org/&amp;source=gmail&amp;ust=1655394848469000&amp;usg=AOvVaw21SwF91tQPQTb9NwPzRP-P">CPH Activity Finder</a>. Credits may also be used to qualify you for continuing education through your employer or professional organization. Use this certificate to document completion of the curriculum. </p>
			<p>
				<?php if ($record->getField('Smart_Posttest_Score') > 79) { ?>
			</p>
			<p><a href="certificate.php" class="button">Print Certificate</a></p>
			<?php } else { ?>
			<p class="alert"><i class="mch-exclamation-triangle"></i> Please return to the post-test to try again.</p>
			<?php } ?>
		</section>


	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-rwdImageMaps/1.6/jquery.rwdImageMaps.min.js" integrity="sha512-eZB7hQa0bRlrKMQ2njpP0d/Klu6o30Gsr8e5FUCjUT3fSlnVkm/1J14n58BuwgaMuObrGb7SvUfQuF8qFsPU4g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
$(document).ready(function(e) {
	$('img[usemap]').rwdImageMaps();
	$('#modules_completed').text("<?php echo $modules_completed; ?>/36");
});
</script>
<?php include('incl/footer.html'); ?>
