<?php
$section = 'trainings';
$page = 'training';
$page_title = "Trainings";
include( '../../incl/header.html' );
?>
<script src="https://cdn.ncemch.org/js/jquery/jquery.min.js"></script>

<script src="https://www.mchnavigator.org/transformation/ebdm/jquery.rwdImageMaps.min.js"></script>
<script>
      $(document).ready(function(e) {
      $('img[usemap]').rwdImageMaps();
      });
</script>
<div class="container" style="margin-top: 2rem; margin-bottom: 2rem;">
  <?php include('../../incl/leftnav.html'); ?>
  <div class="nine columns">
    <?php include('../../incl/title.html'); ?>
    <h2>MCH Academic Legacy Project</h2>
    <h2>DRAFT of Phase 2</h2>
    <p><img src="../../images/mch-legacy.jpg" width="300" height="200" alt="Decorative image of story telling" class="right border" />This project documents the unique paths of MCH leaders in academe. The hope of this project is to preserve these experience and the wisdom from the field that each expert brings and also to inspire a new generation of MCH academics.</p>
    <p>The interviews with each of these MCH academics provide real-life examples of Competency 9: Developing Others Through Teaching, Coaching, and Mentoring.</p>
    <p><strong>Choose a topic from the &quot;Roadmap of MCH academe&quot; below to access a variety of responses from emerging and established academics in the field.</strong> If you can't use the graphical interface, links are provided below.</p>
    <p><img src="../../images/Legacy-2-Roadmap.png" style="height: auto; width: 100%;" usemap="#rwdImageMaps"  />
      <map name="rwdImageMaps">
        <area shape="circle" coords="167,135,121" href="p2-q1.php">
        <area shape="circle" coords="336,340,118" href="p2-q2.php">
        <area shape="circle" coords="512,149,125" href="p2-q3.php">
        <area shape="circle" coords="680,346,117" href="p2-q4.php">
        <area shape="circle" coords="848,144,124" href="p2-q5.php">
      </map>
    </p>
    <p><strong>Alternate Access to the Interviews. </strong>Interview topics with each of these MCH academics:</p>
    <ul>
      <li><a href="p2-q1.php">Career to date and becoming a leader or co-leader of an MCH training program</a>.</li>
      <li><a href="p2-q2.php">Involvement  you with state MCH/Title V programs and other critical MCH Initiatives</a>. </li>
      <li><a href="p2-q3.php">Challenges and concerns for academics</a>.</li>
      <li><a href="p2-q4.php">Credit for you successes</a>.</li>
      <li><a href="p2-q5.php">Tips for becoming a successful MCH Academic</a>. </li>
    </ul>
    <h2><i class="icon mch-icon" aria-hidden="true"></i> Meet the Academic Contributors</h2>
    <p>We want to thank the many MCH academic professionals who spent the time to meet with us and discuss their insights into their careers. These include:</p>
    <br>
    <button class="accordion">Gigliola Baruffi</button>
    <div class="panel"> <img src="../../images/Gigliola-Baruffi.png" alt="Gigliola Baruffi" class="right ppic" />
      <p>Gigliola Baruffi is professor emerita at the University of Hawaii John A. Burns School of Medicine, Department of Public Health Sciences. She obtained her MD degree at the University of Milan, Italy, the MPH, Pediatric and Preventive Medicine Residencies at the Johns Hopkins University. After several years of international work with the United Nations in India and Bangladesh, she joined academe first in the department of MCH, the Johns Hopkins School of Hygiene and Public Health and then the University of Hawaii School of Public Health/School of Medicine.</p>
      <p>As director of the MCH Training Grant she supported students and encouraged fellows. She oversaw a program of yearly CE activities for MCH professionals of the Pacific Islands Nations. After the School of Public Health became a Department of Public Health Sciences in the School of Medicine, Dr. Baruffi developed the MCH Leadership Certificate, fully accredited by the University and much appreciated by Hawaii and Pacific Islands students.</p>
      <p>Her teaching stressed the importance of data in the management of MCH programs and her research interest focused on differences in pregnancy outcomes and young children growth between ethnic groups in Hawaii. Earlier in her career, in recognition of her international work in India and Bangladesh and in academe Dr. Baruffi has been awarded the title of Cavaliere d&rsquo;Italia and the honorary citizenship of the city of Caravaggio (her residence in Italy). After she retired in 2007, she continued to participate in the Title V program applications review of the Pacific Islands; and still is an active member of the MCHJ editorial group. </p>
    </div>
    <button class="accordion">Noel Chavez</button>
    <div class="panel"> <img src="../../images//Noel-Chavez.jpg" alt="Noel Chavez" class="right ppic" />
      <p>Dr. Noel Chávez is an Associate Professor Emerita in the Community Health Sciences Division of the University of Illinois School of Public Health. Her research centers on the health and nutrition status of Latinos and other underrepresented groups, particularly that of children and families. Dr. Chávez&rsquo;s research projects focus on Latino child health, including studying maternal environmental and dietary influences on subsequent development of asthma in children, dietary acculturation, family health and nutrition attitudes, and behaviors in Latinx families with young children.</p>

      <p>Dr. Chávez has served as a proposal reviewer for the USDA NIFA Childhood Obesity Research panel, and is a member of the editorial boards for the <em>Journal of Nutrition Education and Behavior</em> and the <em>Maternal and Child Health Journal</em>. She served on an IOM Panel to Examine the adequacy of food resources and SNAP allotments. She is an active member of both the Food and Nutrition Section where she served as Section Chair, and the Latino Caucus of the American Public Health Association.</p>
    </div>
      <button class="accordion">Martha Coulter</button>
    <div class="panel"> <img src="../../images/martha-coulter.jpg" alt="Martha Coulter" class="right ppic" />
      <p>Dr. Martha Coulter is professor in the Department of Community and Family Health at the USF College of Public Health, maternal and child health has been at the forefront of her public health passion for decades.</p>
      <p>Upon earning her master&rsquo;s degree in public health from the University of California at Berkeley in 1977, she&rsquo;s devoted her public health career to bettering the lives of families and children. Coulter also holds a DrPH from the University of North Carolina at Chapel Hill in maternal and child health. She served as the state program director of the Developmental Evaluation Centers Program at the North Carolina Division of Health Services and as a lecturer at the UNC School of Public Health.</p>

      <p>When she moved to Florida in 1985, she joined the COPH as an assistant professor. In 1986 she also served as the health officer for Prevention and Early Intervention at the Florida Department of Health in Children&rsquo;s Medical Services where she was tasked with implementing the newly passed Public Law 99-457 which provides early intervention services to infants and young children.</p>
      <p>In 1994 she was named Director of the USF COPH&rsquo;s Harrell Center for the Study of Family Violence, a center focused on integrating knowledge with best practices to strengthen community responses to family violence. The center conducts and translates research into usable information for practitioners to provide education and training, as well as serves as an advocacy center.</p>
    </div>
      <button class="accordion">Julie Deardorff</button>
    <div class="panel"> <img src="../../images/Julie-Deardorff.jpg" alt="Julie Deardorff" class="right ppic" />
      <p>Julianna Deardorff, PhD is an Associate Professor in the Division of Community Health Sciences and head of the Maternal, Child and Adolescent Health program, in the School of Public Health at UC Berkeley, where she teaches graduate level courses in Adolescent Health and Evaluation of Health and Social Programs. She is the Director of UC Berkeley’s MCHB-funded Center of Excellence. </p>
      <p>Julianna holds masters and doctorate degrees in clinical psychology, with an emphasis on adolescence, and completed her clinical internship at Lucile Packard Children’s Hospital at Stanford University. Before joining the School of Public Health, she was Assistant Professor in Epidemiology and Biostatistics at UCSF. Julianna’s research focuses on pubertal development, sexual and reproductive health during adolescence and young adulthood, mental health, and related risk and protective factors, particularly among young Latinos in the US. She also has expertise in social and contextual factors related to early adversity, pubertal timing and health outcomes.</p>
    </div>
      <button class="accordion">Eugene DeClercq</button>
    <div class="panel"> <img src="../../images/Eugene-Declercq.jpg" alt="Eugene Declercq" class="right ppic" />
      <p>Eugene DeClercq combines formal training in political science with almost twenty years of experience as a certified childbirth educator to examine policy and practice related to childbirth in the US and abroad. His recent work in examining maternal mortality and morbidity in the US has emphasized the importance of systems approaches to improving women&rsquo;s health. This requires a focus on women&rsquo;s health in the community as well as in clinical settings and not only during pregnancy, but throughout the lifecourse. He is part of the collaborative team that has completed three national studies and a 2018 statewide study of women's experiences in childbirth entitled Listening to Mothers.</p>
      <p>Dr. DeClercq was principal investigator on two NIH funded collaborative projects examining child and maternal outcomes associated with Assisted Reproductive Technologies (MOSART project) and is one of the founders of the Pregnancy to Early Life Longitudinal (PELL) data system that has linked vital statistics, hospital, and administrative data on more than 1,100,000 births in Massachusetts since 1998. He has also been active in a variety of public health projects in his hometown of Lawrence, Massachusetts. As an educator, he is a past president of the Association of Teachers of Maternal and Child Health and has been a recipient of the Norman Scotch Award for outstanding teaching at BUSPH. He is also a recipient of the Martha May Eliot Award from the American Public Health Association for service to maternal and child health and the Greg Alexander award for research in maternal and child health epidemiology. He is currently the BUSPH Assistant Dean for DrPH Education.</p>
    </div>
    <button class="accordion">Trish Elliot</button>
    <div class="panel">
      <p><img src="../../images/trish-elliott.jpg" alt="Trish Elliot" class="right ppic" />Trish Elliott, DrPH, is a Clinical Associate Professor of Community Health Sciences dedicated to training future practitioners of public health. She teaches courses in maternal child and adolescent health, leadership, and program management. Dr. Elliott uses a combination of simulation, case method, and practice-based learning in the classroom and is committed to using innovative approaches in academic-practice collaboration. Dr. Elliott directs the Practice Fellowship Program of the Maternal and Child Health Center of Excellence, connecting exceptional master's degree students with year-long placements in public health organizations, and leads a multi-state initiative to facilitate co-learning for public sector MCH workforce development.&nbsp;&nbsp;She serves as the Director of the Doctor of Public Health program, a school-wide doctoral degree in leadership, management, and policy, preparing students for high-level positions in public health practice, and&nbsp;as the Director of Education for the Department of Community Health Sciences.&nbsp; </p>
      <p>Dr. Elliott&rsquo;s academic and practice interests focus on using implementation science, systems science, and process evaluation methods to improve the health of vulnerable populations. She is particularly interested in adolescent and family access to health services, the intersection of mental health and juvenile justice, school health, academic-practice partnerships, and health policies at the local, state, and federal level. Dr. Elliott joined the department of Community Health Sciences as faculty in 2013, after teaching for four years in an adjunct capacity. Prior to her work in academe, she spent ten years in management within the health sector overseeing complex projects.  She received a BA in Psychology from Colby College, a MPH degree with dual concentrations in Social and Behavioral Sciences, and Maternal and Child Health from Boston University where she also completed her DrPH in Maternal and Child Health. </p>
    </div>
      <button class="accordion">Bernard Guyer</button>
    <div class="panel"> <img src="../../images/Bernard-Guyer.jpg" alt="Bernard Guyer" class="right ppic" />
      <p>Bernard Guyer (currently retired) has conducted research focused on improving the health of children, their mothers, and their families -- in this country and in the developing world -- using the tools of public health. The specific areas of his research included, immunization against vaccine-preventable diseases, childhood injury and injury prevention, the causes and strategies to reduce infant mortality, and interventions to strengthen human development during the early portion of the lifespan.</p>
      <p>A physician trained in both preventive medicine and pediatrics, Dr. Guyer served for seven years as director of the state MCH program in Massachusetts, and for five years as a CDC medical epidemiologist with national and international service. He has chaired or been a member of both state and national committees on childhood injury prevention, outreach for prenatal care, infant mortality, and Medicaid. Dr. Guyer and colleagues at both Harvard and Hopkins have further contributed to providing research that can be used to strengthen the way in which the MCH field addresses its most pressing problems across the lifespan.</p>
    </div>
      <button class="accordion">Arden Handler</button>
    <div class="panel"> <img src="../../images/ardenhandler.jpg" alt="Arden Handler" class="right ppic" />
      <p>Dr. Arden Handler is the Director of the Center of Excellence in Maternal and Child Health and a Professor in the Community Health Sciences division of the UIC School of Public Health. Dr. Handler&rsquo;s research career reflects her long-standing commitment to improve the health of women, children and families, with specific interests in exploring the factors that increase the risk for adverse pregnancy outcomes and examining ways in which the health care delivery system, particularly how prenatal care, postpartum care, and preconception/interconception/well-woman care can ameliorate these risks. Other research and teaching interests include maternal and child health advocacy and policy, building the analytic capacity of the MCH workforce (MCH epidemiology), and the structure and functioning of the public health delivery system.</p>
      <p>Dr. Handler is a founding Board Member of EverThrive (formerly the Illinois Maternal and Child Health Coalition), co-chair of Illinois&rsquo; subcommittee on the Social Determinants of Health as part of the Collaborative Improvement &amp; Innovation Network to Reduce Infant Mortality (CoIIN), and is a former member of the Secretary&rsquo;s Advisory Committee on Infant Mortality (SACIM). She was the 2016 recipient of the Maternal and Child Health Bureau&rsquo;s, Vince Hutchins Partnership Award. She is a nationally renowned leader in maternal and child health advocacy, policy, epidemiology, and public health system improvement.</p>
    </div>
      <button class="accordion">Carol Hogue</button>
    <div class="panel"> <img src="../../images/Carol-Hogue.jpg" alt="Carol Hogue" class="right ppic" />
      <p>Carol Hogue began her career as a social worker in Knoxville, Tennessee, and later moved to North Carolina in 1969 where she earned an MPH and PhD in Epidemiology (minor Biostatistics) from the University of North Carolina at Chapel Hill in 1971 and 1973. Hogue is most widely known for using surveillance systems, developing psychosocial measurement of racial disparities, and conducting groundbreaking epidemiologic studies of perinatal outcomes.</p>
      <p>At CDC, she developed national linkage of birth and infant death surveillance. Her analyses of this system revealed that high educational attainment was not protective against the racial gap in African American infant deaths and triggered further, ongoing research into discrimination as a risk factor for maternal and infant health. Hogue also led the development of CDC&rsquo;s Pregnancy Risk Assessment Monitoring System (PRAMS) that provides unique data for research, governmental programming, and evaluation. Hogue&rsquo;s study of the effects of induced abortion on subsequent fertility challenged accepted knowledge from case-control studies, and its methodology continues to be the gold standard to assess long-term health effects of abortion. She served as Lead Epidemiologist for the Stillbirth Collaborative Research Network&rsquo;s population-based case-control study of stillbirth. In 1992 Hogue was appointed to the Jules and Uldeen Terry Chair of Maternal and Child Health at Emory University&rsquo;s Rollins School of Public Health and established the Women&rsquo;s and Children&rsquo;s Center.</p>
    </div>
    <button class="accordion">Charvonne Holliday</button>
    <div class="panel"> <img src="../../images/charvonne-holliday.png" alt="Charvonne Holliday" class="right ppic" />
      <p>Charvonne N. Holliday, PhD, is trained in behavioral and community health, with research experience and public health practice related to women’s health and community-oriented approaches to positive change.</p>
      <p>Dr. Holliday is committed to understanding racial/ethnic disparities that persist in intimate partner violence (IPV) and women’s sexual/reproductive health by examining social and structural determinants of health. Current research includes examining racial/ethnic differences in reproductive coercion and women’s contraceptive decision making, mitigating barriers to help-seeking for survivors of IPV, and exploring innovative intervention strategies for male IPV perpetrators. I apply a mixed-methods approach, including participatory research methods like concept mapping.</p>
      <p>Current research includes examining racial/ethnic differences in reproductive coercion and women’s contraceptive decision making, mitigating barriers to help-seeking for survivors of IPV, and exploring innovative intervention strategies for male IPV perpetrators. Dr. Holliday applies a mixed-methods approach, including participatory research methods like concept mapping.</p>
    </div>
    <button class="accordion">Colleen Huebner</button>
    <div class="panel"> <img src="../../images/colleen-huebner.png" alt="Colleen Huebner" class="right ppic" />
      <p>Colleen Huebner’s background is in Developmental Psychology (PhD) and Epidemiology (MPH). She was a faculty member of the University of Washington’s Center of Excellence in MCH Education, Science and Practice for 25 years as a teacher, assistant director, director (Principal Investigator) and professor emeritus. Within the University of Washington’s School of Public Health, she taught courses in needs assessment, program planning and evaluation, health policy, and the historical and current influence of Title V on women, children and families in the U.S. She mentored the research of over 70 MPH students, PhD students and post-docs and helped guide many of their projects to peer-reviewed publication.</p>
      <p>Her own research focused on the design, implementation and evaluation of community- and clinic-based preventive intervention programs for young children and families in poverty including programs to prevent infant maltreatment, promote early language development, emergent literacy and protect children’s oral health. She was a member of several interdisciplinary research teams at the University and worked with numerous collaborators including families and practitioners in rural communities in Washington, Oregon, Colorado, and in Alaska Native villages; people working in public libraries, community health clinics, Head Start programs, early intervention and family centers in Seattle, Chicago, and in the Republic of the Marshall Islands. A common goal of Dr. Huebner’s research was to establish the evidence for effective, feasible policies and programs that support young children’s health and development and, in turn, disseminate those practices broadly to benefit all children and families in need. In acknowledgment of this work, she served as a Presidential Appointee to the U.S. National Commission on Libraries and Information Science (2003-2007).</p>
      <p>Dr. Huebner, along with colleagues in MCH academe, field-based public health and clinical practice, established the groundwork for several MCH resources of national scope including the MCH Leadership Competencies and the MCH Navigator. She was on the editorial board of the <em>Maternal and Child Health Journal</em> for many years and, in 2005, received the Loretta P. Lacey Academic Leadership Award of the Association of Teachers of Maternal and Child Heath.</p>
    </div>
    <button class="accordion">Russell Kirby</button>
    <div class="panel">
      <p><img src="../../images/Russell-Kirby.jpg" alt="Russell S. Kirby" class="right ppic" />Russell S. Kirby, Ph.D., M.S., F.A.C.E., Distinguished University Professor, Marrell Endowed Chair, and Faculty Strategic Area Lead for Population Health Science, University of South Florida</p>
      <p>Dr. Russell Kirby is a perinatal and pediatric epidemiologist trained in the social sciences, with a PhD in human geography (Wisconsin, 1981) and MS in preventive medicine-epidemiology (Wisconsin, 1991). Dr. Kirby worked at the state health agencies in Wisconsin and Arkansas, on the faculties of the Department of Pediatrics, University of Arkansas for Medical Sciences, and Department of Obstetrics and Gynecology, Milwaukee Clinical Campus, University of Wisconsin Medical School, and the School of Public Health, University of Alabama-Birmingham prior to joining the faculty of the University of South Florida in 2008.  He was elected Fellow in the American College of Epidemiology in 1996, and served as president in 2018-19. Dr. Kirby previously served as President of the National Birth Defects Prevention Network, the Wisconsin Association for Perinatal Care and the Arkansas Perinatal Association, Society for Pediatric and Perinatal Epidemiologic Research, and the Association of Teachers of Maternal and Child Health. </p>
      <p>Dr. Kirby has authored more than 300 peer-reviewed articles, with more than 500 different co-authors, and actively participates in the editorial process as a peer reviewer or editorial board member for numerous journals. While his research interests focus on the public health implications of health policies and programs, with special reference to perinatal and maternal/child health; population health informatics; and perinatal/pediatric studies in genetics, birth defects, and developmental disabilities, clinical research, study design and analysis, birth defects surveillance and epidemiology has been a major interest since the early 1980s.</p>
    </div>
      <button class="accordion">Jonathan Kotch</button>
    <div class="panel"> <img src="../../images/Jonathan-Kotch.jpg" alt="Jonathan Kotch" class="right ppic" />
      <p>Dr. Jonathan Kotch, a board-certified medical specialist in pediatrics and preventive medicine, was on the active faculty of the Department of Maternal and Child Health for 38 years. Currently emeritus research professor, he was the Carol Remmer Angle Distinguished Professor of Children's Environmental Health until he entered phased retirement in 2013. He edited the first three editions of <em>Maternal and Child Health: Programs, Problems, and Policy in Public Health</em>(Jones and Bartlett) and is the recipient of the Martha May Eliot Award (APHA), the John C. MacQueen Lectureship (AMCHP), the Academic Leadership Award (ATMCH), and the Young Professional of the Year Award (MCH Section).</p>
      <p>His expertise in health and safety in out-of-home child care has resulted in national training programs for child care health consultants across the country, and he was co-chair of the steering committee that produced the third edition of Caring for Our Children: National Health and Safety Performance Standards; Guidelines for Early Care and Education Programs.</p>
      <p>As the Principal Investigator of one of five local sites of the Longitudinal Studies Consortium on Child Abuse and Neglect, Dr. Kotch was responsible for the North Carolina cohort, studied from birth until age 18. He was PI for all 5 sites and the coordinating center of LONGSCAN's last two years. A follow-up funded by NIDA has just concluded (2019).</p>
    </div>
      <button class="accordion">Milton Kotelchuck</button>
    <div class="panel"> <img src="../../images/Milton-Kotelchuck.jpg" alt="Milton Kotelchuck" class="right ppic" />
      <p>Milton Kotelchuck, PhD, MPH, is currently Professor of Pediatrics at Harvard Medical School and Senior Scientist in Maternal and Child Health at the Center for Child &amp; Adolescent Health Research and Policy at Massachusetts General Hospital. Formerly, he was Professor and Chair of the Maternal and Child Health Departments at Boston University School of Public Health and at the University of North Carolina at Chapel Hill.</p>

      <p>Dr. Kotelchuck has been active in advancing MCH research, practice, policy and training in the MCH field for nearly 50 years; to that end, he has served on numerous local, State, national and professional MCH advisory committees. He has advocated for the advancement of MCH epidemiology and data systems and for the reintegration of MCH life course/social determinant of health perspectives into the MCH field.. His own research interests include examination of the adequacy and content of prenatal care, racial disparities in birth outcomes, maternal morbidity, immigrant health, child nutrition, fatherhood/men&rsquo;s health, child health services, and health data policy. Dr. Kotelchuck has extensively evaluated public health programs to improve birth outcomes and child health status. He developed the widely used Adequacy of Prenatal Care Utilization (APNCU) Index, the so-called Kotelchuck Index. He served as the founding and initial Editor of the <em>Maternal and Child Health Journal</em>.</p>
      <p>In 2000, Dr. Kotelchuck was awarded the first National MCH Epidemiology Award for &ldquo;Advancing Knowledge&rdquo; from the Coalition for Excellence in MCH Epidemiology. In 2010, he was awarded the Martha May Eliot Award, the top honor given for Maternal and Child Health by the American Public Health Association.</p>
    </div>
    <button class="accordion">Michael Kramer</button>
    <div class="panel">
      <p><img src="../../images/michael-kramer.jpg" alt="Michael Kramer" class="right ppic" />Michael Kramer, PhD, MMSc, is a social epidemiologist, health disparities scholar, and the Director of the Emory Center of Excellence in Maternal and Child Health Education, Science, and Practice. He was also a HRSA MCHB trainee himself. His research seeks to advance theory for the social determinants of health, develop and implement novel methods for measuring and quantifying the biological embodiment of social experiences and environments, and advancing impactful science focusing on improving the health of women and children. His research has been supported by NIH, HRSA, CDC, and March of Dimes. </p>
      <p>Dr. Kramer's current projects focus on building the evidence base to inform social and community policies to eliminate disparities in severe maternal morbidity and mortality. He currently serves as the co-chair of the Georgia maternal mortality review committee.</p>
    </div>
      <button class="accordion">Lew Margolis</button>
    <div class="panel"> <img src="../../images/margolis_lewis_200sq.jpg" alt="Lew Margolis" class="right ppic" />
      <p>Dr. Lew Margolis is a veteran MCH educator who most recently was an associate professor in the Department of Maternal and Child Health at the UNC Gillings School of Global Public Health.</p>
      <p>Dr. Margolis served on the faculty at the Gillings School for 28 years, during which he earned a reputation among MCH students as a passionate and dedicated teacher, mentor and advisor. He was especially committed to challenging students to think critically and consider the many sides of complex public policy issues. Margolis retired from teaching at the Gillings School in 2018, although his impact on the field continues as his many students advance in their MCH careers.</p>

      <p>Dr. Margolis started his career as a pediatrician. After developing an interest in the social determinants of health, he earned a master's in epidemiology at UNC. From there, he combined his passions for public health and the well-being of children to begin his career in MCH academe. He was a co-lead of the UNC MCH Interdisciplinary Leadership Development program which brought together students and faculty from five MCHB-funded training programs. He is the recipient of the Vince Hutchins Leadership Award from the Association of Maternal and Child Health Programs, as well as the Edward G. McGavran Award for Excellence in Teaching and the Department of Maternal and Child Health Teaching Award.</p>
    </div>
    <button class="accordion">Lois McClosky</button>
    <div class="panel">
      <p><img src="../../images/Lois-McClosky.jpg" alt="Lois McCloskey" class="right ppic" />Lois McClosky, DrPH, began her public health career 30 years ago as an applied anthropologist and educator of community health workers in Nepal. The work inspired her lifelong concern with the health care of women and their infants, particularly in communities that are under-served. In both international and domestic settings, her work focuses on the disconnects between the lives of women and the health care systems meant to serve their needs across the life course and proven strategies for engaging and activating women to be full partners in their reproductive health care and planning. She is currently supported by the NICHD and NIDDK to study the barriers to follow-up testing and prevention for women with gestational diabetes, a harbinger of risk type 2 diabetes mellitus later in life. At BUSPH she serves as Associate Chair of the Department of Community Health Sciences, Co-Director of the MCH Certificate, and Director of the Center of Excellence in Maternal and Child Health, a Center dedicated to the education of a diverse MCH workforce, ready to lead. As an educator, she specializes in practice-based courses that engage students in the application of their skills and knowledge in real life organizations, addressing real life challenges. Currently she teaches &ldquo;Implementing Community Health Initiatives: A Field-based Course in Leadership and Consultation&rdquo; and &ldquo;Sexual and Reproductive Health Advocacy: From Rights to Justice.&rdquo;</p>
      <p> Dr. McClosky completed an MPH in population, family and international health and a DrPH in perinatal epidemiology and health services research at UCLA School of Public Health. Upon graduation, she co-founded the Institute for Urban Health Policy and Research for the Boston Department of Health and Hospitals and served as its Senior Research Scientist for 7 years before joining the faculty of Boston University. During her tenure at the Institute, she led research and community action initiatives designed to mobilize community residents, health professionals, academics, and policy-makers to eliminate racial disparities in infant death and pre-term birth. The findings led to fundamental changes in how perinatal health services are delivered to women of African descent in Boston. She directed the launch of a study abroad program, &ldquo;IHP: Health and Community&rdquo;, dedicated to comparative study of health, systems and culture in four countries. She co-founded the Women&rsquo;s Health Committee of the MCH Section of the American Public Health Association, is a member of the Association of Teachers of Maternal and Child Health, and serves on the peer review panels of the Women&rsquo;s Health Journal, the Maternal and Child Health Journal, the Journal of the Poor and Under-served, and Public Health Reports, BMC Health Services, and BMC Pregnancy and Birth. </p>
    </div>
      <button class="accordion">Marie C. McCormick</button>
    <div class="panel"> <img src="../../images/Marie-McCormick.jpg" alt="Marie McCormick" class="right ppic" />
      <p>Marie C. McCormick is a pediatrician with a second doctorate in health services research. She was born in Massachusetts and attended Emmanuel College, Boston, from which she graduated Magna cum Laude in 1967. She then went to Johns Hopkins Medical School completing her MD in 1971. Following that she did a pediatric residency at Johns Hopkins Hospital while completing her doctoral work for a Doctor of Science in the Johns Hopkins School of Public Health (awarded in 1978). Her initial faculty appointment was at the University of Illinois in Chicago, but she returned quickly to Hopkins to join the Health Services Research Center there as the project director of the evaluation of the National Perinatal Regionalization Program funded by the Robert Wood Johnson Foundation RWJF). In 1981, she moved to the University of Pennsylvania, Department of Pediatrics, and in 1987, she joined the faculty of the Department of Pediatrics at Harvard Medical School and, in 1991, she became Professor and Chair of the Department of Maternal and Child Health at the Harvard School of Public Health, and Professor of Pediatrics. She is currently the Sumner &amp; Esther Feldberg Professor of Maternal &amp; Child Health Emerita in the Department of Social and Behavioral Sciences at the Harvard T. H. Chan School of Public Health, and Senior Associate for Academic Affairs in the Department of Neonatology at the Beth Israel Deaconess Medical Center.</p>

      <p>The evaluation of the RWJF program launched an investigative career in two interconnected areas of research: the outcomes of high-risk, especially premature, infants and evaluation of programs to improve perinatal outcomes. As part of the evaluation of the RWJF program, the one-year outcomes, data on about 10,000 children were obtained, at the beginning of the program and at midpoint. This large sample permitted examination of outcomes beyond the traditional ones of cerebral palsy and low IQs. The results were among the first to document the post-NICU use of health services, and to examine contextual factors affecting outcomes. The final results showed no increase in neurodevelopmental disability following sharp decreases in birth-weight specific mortality, addressing a criticism of the use of neonatal intensive care. In addition, the overall results contributed to the use of the proportion of infants weighing less than 1500 grams born in Level III hospitals as a marker of regionalization. In a follow-up effort, she reconstructed portions of this cohort plus that of a large multisite trial involving very low birth weight infants at school age. In this study, she applied instrumentation designed to capture the elements of the WHO definition of health. In doing so, she was among the first to establish the risk of lower birth weights for a greater range of adverse outcomes like behavioral problems, as well as the health services and educational needs of these infants. An important element arising from this approach was the focus on the functional impact of perinatal events, not just diagnoses.</p>
      <p>Besides the RWJF program, she also was a co-investigator of the evaluation of the original national Healthy Start Program. Her primary responsibility was the analysis of a survey of post-partum women in the target communities to estimate participation rates and access to services. The results clearly supported the role of Healthy Start in enhancing the use of case management. In addition, she also documented the use of Fetal and Infant Mortality Reviews in this program. On the theme of increasing access to services, she and a colleague evaluated a small program at Harlem Hospital using several techniques to encourage early use of prenatal care including community health workers to identify pregnant women and enroll them in care. The evaluation provided some of the first results on the productivity and cost of such an effort.</p>
      <p>An effort that combined both streams of research was the Infant Health and Development Program (IHDP). This research examined the role of early educational intervention in improving the outcomes of premature, low birth weight infants in a multi-site trial. Phase I of the project included the provision of a combination of home-visiting and center based developmental services, with longitudinal follow-up until age 18 years. During this time, she had a variety of roles in the project from the Research Steering Committee in Phase I to site director in the follow-up to age 8 and overall principal investigator of the 18-year assessment. The results clearly supported a major influence on development (as measured by IQ) even for the tiniest infants, and a substantial advantage among heavier infants at 18.</p>
      <p>In her role at the Harvard T. H. Chan School of Public Health, she has been the director of the Maternal and Child Training program, now Center of Excellence. In that role, she has expanded the program to be school-wide, attracting a diverse group of students.</p>
      <p>She is the member of a number of professional organizations and the recipient of several awards and honors, including Martha May Eliot Forum Invited Speaker, American Public Health Association Meeting, November, 1988.</p>
      <p>Of most significance is her several roles in the Academic Pediatric Association. She is currently the Senior Associate Editor of the Associations journal, and in that role initiated an annual report on health services use for children and youth in the United States. She was elected to membership in the Institute of Medicine, in 1997, and has served on 16 committees, chairing 5. Most notably, her efforts as chair of the Immunization Safety Review Committee earned her the David Rall Medal for exceptional service.</p>
    </div>
    <button class="accordion">Cynthia Minkovitz</button>
    <div class="panel"> <img src="../../images/Cynthia-Minkovitz.jpg" alt="Cynthia Minkovitz" class="right ppic" />
      <p>Cynthia Minkovitz, MD, MPP, is the William H. Gates, Sr. Professor and Chair of the Department of Population, Family and Reproductive Health at Johns Hopkins Bloomberg School of Public Health, and a Professor of Pediatrics in the School of Medicine. Her research focuses on enhancing the quality of preventive services and understanding the impact of systems reforms on the health and well-being of children and families.</p>
      <p>Dr. Minkovitz serves on the Leadership Team for the Home Visiting Applied Research Collaborative (HARC).  HARC’s mission is to promote the use of innovative research methods to advance precision home visiting and to accelerate the integration of results into practice.   Dr. Minkovitz has led national and state evaluations including Healthy Steps for Young Children, the Dyson Community Pediatrics Training Initiative, and New Jersey Project LAUNCH.  She also co-led efforts to develop a framework to promote coordination in the early childhood system and collaborates on New Jersey’s Preschool Development Grant and Maryland’s Prenatal to Three Initiative.</p>
      <p>Dr. Minkovitz is Director of the Johns Hopkins Center of Excellence in MCH; she has led the MCH Postdoctoral Fellowship Program since 2015. Dr. Minkovitz has received numerous awards including the Academic Pediatric Association Research Award as well as institutional awards for excellence in teaching and mentoring.</p>
    </div>
      <button class="accordion">Donna Petersen</button>
    <div class="panel"> <img src="../../images/Donna-Petersen.jpg" alt="Donna Petersen" class="right ppic" />
      <p>Donna Petersen is a professor of public health at the University of South Florida. She earned her masters and doctoral degrees in maternal and child health from the Johns Hopkins School of Hygiene and Public Health. She has held faculty and senior leadership positions at the University of Alabama at Birmingham School of Public Health, at the University of Minnesota School of Public Health, and served as Director of the Division of Family Health at the Minnesota Department of Health.</p>

      <p>Dr. Petersen has provided extensive technical assistance and training to over 25 state health departments in the areas of needs assessment, data system development, systems level accountability and the development of population-based indicators. She has served on numerous boards, commissions and task forces and is Editor Emerita of the <em>Maternal and Child Health Journal</em>, founding member and past president of the National Board of Public Health Examiners, past Chair of the Council on Education for Public Health, and immediate-past Chair of the Association of Schools and Programs of Public Health. </p>
      <p>Dr. Petersen has been honored for her work by the American Public Health Association, the Association of Teachers of Maternal and Child Health, the National Healthy Mothers, Healthy Babies Coalition, the Delta Omega National Public Health Honor Society, the National Coalition for Excellence in MCH Epidemiology, the federal Bureau of Maternal and Child Health and the Association of Maternal and Child Health Programs.</p>
    </div>
      <button class="accordion">Cheri Pies</button>
    <div class="panel"> <img src="../../images/Cheri-Pies.jpg" alt="Cheri Pies" class="right ppic" />
      <p>Cheri Pies is a clinical professor emerita at the UC Berkeley School of Public Health and served as the Principal Investigator for the Best Babies Zone Initiative from 2012 to 2019, a place based multi-sector approach to reducing infant mortality through community driven transformation. As one of the pioneers in understanding social determinants of health, she has worked to address the ways in which social and economic disparities and inequities influence birth outcomes and generational health across the life course. Dr. Pies received her MSW from Boston University in 1976. She earned her MPH (1985) and DrPH (1993) from the University of California at Berkeley.</p>

      <p>When asked about the secrets of success she states: &ldquo;Collaboration is my touchstone—with colleagues and students. Learning from one another is the high point of my time at Berkeley. I have learned an enormous amount from the amazing and remarkable students that I have had the privilege of teaching over the past many years—both in MCH and the DrPH Programs. And in order to succeed in the field, one needs to network, know their colleagues, understand what the work is that others are doing, and be able to work together with one another effectively and collaboratively.&rdquo;</p>
    </div>
    <button class="accordion">Terri Powell</button>
    <div class="panel">
      <p><img src="../../images/terri-powell.jpg" alt="Terri Powell" class="right ppic" />Terrinieka W. Powell, PhD, is an Associate Professor in the Department of Population, Family and Reproductive Health  at Johns Hopkins Bloomberg School of Public Health. She has an extensive history of using community-engaged approaches and working with community partners (e.g., churches, libraries and youth-oriented CBOs) to conduct research. She has expertise in adolescent health, qualitative methods, intervention development and implementation science. She has collaborated with institutions across several states to promote educational attainment as well as prevent teen pregnancy, HIV, and substance use among adolescents. She has over 40 publications and has been PI or Co-I on 10 externally funded grants that seek to improve the lives of vulnerable young people.</p>
    </div>
    <button class="accordion">William Sappenfield</button>
    <div class="panel">
      <p><img src="../../images/william-sappenfield.png" alt="William Sappenfield" class="right ppic" />William M. Sappenfield, MD, MPH, CPH is Professor and Director of the Chiles Center at the College of Public Health, University of South Florida. He also serves as Director of the Florida Perinatal Quality Collaborative (FPQC), a statewide multi-organizational effort to improve health and health care quality of mothers and infants.  As both a pediatrician and an epidemiologist, Dr. Sappenfield has 35 years of experience in epidemiological and public health research, teaching, and practice in maternal and child health at a community, state and national level.</p>
      <p> As a nationally recognized leader in the field of maternal and child health epidemiology, Dr. Sappenfield spent the first 22 years of his career as a CDC medical epidemiologist working on assignment with state and local public health agencies to enhance their capacity to use epidemiology, evaluation and research to improve the health of the women and children.  This includes being assigned to work directly in three state public health agencies as well as at CityMatCH, a national organization support MCH in urban health departments.  He completed his CDC career serving four years as Team Leader of the MCH Epidemiology Program directly responsible for the national MCH EPI effort including training, mentoring and supporting maternal and child health epidemiologists around the nation.</p>
      <p>Upon retiring from the CDC and the U.S. Public Health Service, Dr. Sappenfield served six years at the Florida Department of Health as the State MCH Epidemiologist and as Unit Director for the MCH Practice and Analysis Unit. His responsibilities included leading the Department&rsquo;s research, epidemiology, evaluation and health data efforts to guide policies and programs for Florida mothers and children at a state and community level.</p>
      <p>In recent years working at the Chiles Center, Dr. Sappenfield is one of the leader to develop the FPQC which has emerged as a multi-partner collaborative supporting hospitals and providers in improving the quality of health care provided to mothers and infants.  These efforts include reducing the rate on non-medially indicated early term deliveries, managing maternal hemorrhage at delivery, treating maternal hypertension in a timely fashion, promoting use on mother&rsquo;s own milk in the ICU, reducing primary cesareans, promoting access to immediate postpartum use of LARC, and improving the health care of mothers with opioid use disorder and their babies.  FPQC currently works with 86 Florida delivery hospitals that serve 86% of the state mothers and their newborns and has made measurable improvements in the state maternal and infant health outcomes as well as reduce health care costs.</p>
      <p>Dr. Sappenfield&rsquo;s other significant maternal and child health contributions include:  early developments in the community-based fetal, infant and maternal mortality reviews, adapting an applied approach to investigating a community&rsquo;s infant mortality problem called &ldquo;Perinatal Periods of Risk,&rdquo; developing core state indicators for monitoring preconception health and MCH life course, and promoting best practices in maternal and child health epidemiology.  Dr. Sappenfield has received multiple awards including the 2003 National MCH Epidemiology Award for Outstanding Leadership, the 2012 Elaine Whitelaw National Volunteer Service Award by the March of Dimes Foundation, the 2014 MCH Bureau Director&rsquo;s Award from Health Resources and Services Administration, the 2016 John C. MacQueen Annual Lectureship Award from the Association of Maternal and Child Health Programs, the 2020 Health Care Hero Award from the Florida Alliance for Healthcare Value, and the 2020 Distinguished Service Award from the American College of Obstetrics and Gynecology.  As the Director, the FPQC was award the 2016 Sapphire Award Recognizing Excellence and Innovation in Community Health for an Organization.</p>
    </div>
    <button class="accordion">Ellen Schafer</button>
    <div class="panel"> <img src="../../images/ellen-schafer.jpg" alt="Ellen Schafer" class="right ppic" />
      <p>Dr. Ellen Schafer earned her Ph.D. in Public Health with an emphasis on  Community and Behavioral Health from the University of Iowa in 2015, and completed a two-year postdoctoral fellowship in Maternal and Child Health at the University of South Florida before coming to Boise State University in 2018. Schafer is a Master Certified Health Education Specialist and received her Masters of Public Health (MPH) in Community Health Education in 2006 from the University of Wisconsin La Crosse.</p>
      <p>Dr. Schafer teaches health promotion and education, and public health classes. Her professional health education experience includes working as a health and wellness specialist with the Greater Southern Tier Board of Cooperative Educational Services, funded by the New York State Tobacco Control Program. She worked with K-12 school districts in New York State to develop, implement, enforce, and evaluate tobacco-free campus policies and educational initiatives. In addition, Schafer worked at the University of Mississippi as the Assistant Director of Student Health for Health Promotion, where she directed and implemented all of the health education and promotion activities on campus for students and staff and participated on the advisory board for the University’s Collegiate Recovery Community.</p>
      <p>Dr. Schafer’s main research objective is to understand the mechanisms by which social context and social network influences are associated with health behaviors, and she typically applies these factors to studies of infant feeding and care.</p>
    </div>
      <button class="accordion">Donna Strobino</button>
    <div class="panel">
      <p><img src="../../images/Donna-Strobino.jpg" alt="Donna Strobino" class="right ppic" />Donna Strobino has devoted her research career to MCH research with a special focus on the health of disadvantaged women during pregnancy and their young children and families. Her major perinatal health research contributions center on understanding the reasons why disadvantaged women have unfavorable pregnancy outcomes, and interventions to improve their outcomes, including among teenagers, low-income women, African American women and women who use drugs during pregnancy.</p>
      <p>More recent research addresses maternal mental health as well as the interface of women&rsquo;s chronic conditions and mental and psychosocial health in pregnancy with an eye to reducing neonatal morbidity as well as the burden of disease as women age. She has also studied the impact of maternal depressive symptoms on young children&rsquo;s behavior and growth as well as parenting behaviors and use of preventive health services. Dr. Strobino currently works collaboratively with students and other faculty on studies of maternal morbidity and its impact on postpartum health, as well as the impact of chronic conditions on morbidity. She has conducted numerous evaluations of perinatal health programs in a variety of settings and pediatric programs for young children. She was Principal Investigator of the national evaluation of Fetal and Infant Mortality Review Programs and was a key investigator for the national Healthy Steps evaluation. She has been the Director of the Center of Excellence in MCH in Education, Science and Practice since 2004 and of the MCH Epidemiology Doctoral Training Program since 2008.</p>
    </div>
    <button class="accordion">Martha Wingate</button>
    <div class="panel">
      <p><img src="../../images/martha-wingate.jpg" alt="Martha Wingate" class="right ppic" />Dr. Martha S. Wingate (DrPH, MPH, UAB; BS, Birmingham-Southern College) is a Professor in the Department of Health Care Organization and Policy. She teaches courses in public health systems, maternal and child health, leadership, and perinatal health issues. Dr. Wingate serves as the Director of the Maternal and Child Health (MCH) Policy and Leadership Concentration. She also serves as the Director of the HRSA-funded Center of Excellence in MCH Education, Science, and Practice.</p>
      <p>She has published in a number of peer-reviewed journals, including American Journal of Public Health, Social Science and Medicine, and American Journal of Obstetrics and Gynecology and is co-author of a textbook on perinatal epidemiology. Her work focuses on preterm birth, fetal and infant mortality, racial and ethnic disparities in birth outcomes, and health policies related to pregnancy and infant health. She is engaged in technical assistance to the MCH workforce at the local, state, and national levels.</p>
    </div>
  </div>
</div>
</div>
<?php include('../../incl/footer.html'); ?>
