<?php
$section = 'trainings';
$page = 'training';
$page_title = "Trainings";
include( '../../incl/header.html' );
?>
<script src="https://cdn.ncemch.org/js/jquery/jquery.min.js"></script>

<script src="https://www.mchnavigator.org/transformation/ebdm/jquery.rwdImageMaps.min.js"></script>
<script>
      $(document).ready(function(e) {
      $('img[usemap]').rwdImageMaps();
      });
</script>
<div class="container" style="margin-top: 2rem; margin-bottom: 2rem;">
  <?php include('../../incl/leftnav.html'); ?>
  <div class="nine columns">
    <?php include('../../incl/title.html'); ?>
    <h2>MCH Academic Legacy Project</h2>
    <h2>DRAFT of Phase 2</h2>
    <p><img src="../../images/mch-legacy.jpg" width="300" height="200" alt="Decorative image of story telling" class="right border" />This project documents the unique paths of MCH leaders in academe. The hope of this project is to preserve these experience and the wisdom from the field that each expert brings and also to inspire a new generation of MCH academics.</p>
    <p>The interviews with each of these MCH academics provide real-life examples of Competency 9: Developing Others Through Teaching, Coaching, and Mentoring.</p>
    <p><strong>Choose a topic from the &quot;Roadmap of MCH academe&quot; below to access a variety of responses from emerging and established academics in the field.</strong> If you can't use the graphical interface, links are provided below.</p>
    <p><img src="../../images/Legacy-2-Roadmap.png" style="height: auto; width: 100%;" usemap="#rwdImageMaps"  />
      <map name="rwdImageMaps">
        <area shape="circle" coords="167,135,121" href="p2-q1.php">
        <area shape="circle" coords="336,340,118" href="p2-q2.php">
        <area shape="circle" coords="512,149,125" href="p2-q3.php">
        <area shape="circle" coords="680,346,117" href="p2-q4.php">
        <area shape="circle" coords="848,144,124" href="p2-q5.php">
      </map>
    </p>
    <p><strong>Alternate Access to the Interviews. </strong>Interview topics with each of these MCH academics:</p>
    <ul>
      <li><a href="p2-q1.php">Career to date and becoming a leader or co-leader of an MCH training program</a>.</li>
      <li><a href="p2-q2.php">Involvement  you with state MCH/Title V programs and other critical MCH Initiatives</a>. </li>
      <li><a href="p2-q3.php">Challenges and concerns for academics</a>.</li>
      <li><a href="p2-q4.php">Credit for you successes</a>.</li>
      <li><a href="p2-q5.php">Tips for becoming a successful MCH Academic</a>. </li>
    </ul>
    <h2><i class="icon mch-icon" aria-hidden="true"></i> Meet the Academic Contributors</h2>
    <p>We want to thank the many MCH academic professionals who spent the time to meet with us and discuss their insights into their careers. These include:</p>
    <br>
    <button class="accordion">Gigliola Baruffi</button>
    <div class="panel"> <img src="../../images/Gigliola-Baruffi.png" alt="Gigliola Baruffi" class="right ppic" />
      <p>Gigliola Baruffi is professor emerita at the University of Hawaii John A. Burns School of Medicine, Department of Public Health Sciences. She obtained her MD degree at the University of Milan, Italy, the MPH, Pediatric and Preventive Medicine Residencies at the Johns Hopkins University. After several years of international work with the United Nations in India and Bangladesh, she joined academe first in the department of MCH, the Johns Hopkins School of Hygiene and Public Health and then the University of Hawaii School of Public Health/School of Medicine.</p>
      <p>As director of the MCH Training Grant she supported students and encouraged fellows. She oversaw a program of yearly CE activities for MCH professionals of the Pacific Islands Nations. After the School of Public Health became a Department of Public Health Sciences in the School of Medicine, Dr. Baruffi developed the MCH Leadership Certificate, fully accredited by the University and much appreciated by Hawaii and Pacific Islands students.</p>
      <p>Her teaching stressed the importance of data in the management of MCH programs and her research interest focused on differences in pregnancy outcomes and young children growth between ethnic groups in Hawaii. Earlier in her career, in recognition of her international work in India and Bangladesh and in academe Dr. Baruffi has been awarded the title of Cavaliere d&rsquo;Italia and the honorary citizenship of the city of Caravaggio (her residence in Italy). After she retired in 2007, she continued to participate in the Title V program applications review of the Pacific Islands; and still is an active member of the MCHJ editorial group. </p>
    </div>
    <button class="accordion">Julie Deardorff</button>
    <div class="panel"> <img src="../../images/Julie-Deardorff.jpg" alt="Julie Deardorff" class="right ppic" />
      <p>Julianna Deardorff, PhD is an Associate Professor in the Division of Community Health Sciences and head of the Maternal, Child and Adolescent Health program, in the School of Public Health at UC Berkeley, where she teaches graduate level courses in Adolescent Health and Evaluation of Health and Social Programs. She is the Director of UC Berkeley’s MCHB-funded Center of Excellence. </p>
      <p>Julianna holds masters and doctorate degrees in clinical psychology, with an emphasis on adolescence, and completed her clinical internship at Lucile Packard Children’s Hospital at Stanford University. Before joining the School of Public Health, she was Assistant Professor in Epidemiology and Biostatistics at UCSF. Julianna’s research focuses on pubertal development, sexual and reproductive health during adolescence and young adulthood, mental health, and related risk and protective factors, particularly among young Latinos in the US. She also has expertise in social and contextual factors related to early adversity, pubertal timing and health outcomes.</p>
    </div>
    <button class="accordion">Trish Elliot</button>
    <div class="panel">
      <p><img src="../../images/trish-elliott.jpg" alt="Trish Elliot" class="right ppic" />Trish Elliott, DrPH, is a Clinical Associate Professor of Community Health Sciences dedicated to training future practitioners of public health. She teaches courses in maternal child and adolescent health, leadership, and program management. Dr. Elliott uses a combination of simulation, case method, and practice-based learning in the classroom and is committed to using innovative approaches in academic-practice collaboration. Dr. Elliott directs the Practice Fellowship Program of the Maternal and Child Health Center of Excellence, connecting exceptional master's degree students with year-long placements in public health organizations, and leads a multi-state initiative to facilitate co-learning for public sector MCH workforce development.&nbsp;&nbsp;She serves as the Director of the Doctor of Public Health program, a school-wide doctoral degree in leadership, management, and policy, preparing students for high-level positions in public health practice, and&nbsp;as the Director of Education for the Department of Community Health Sciences.&nbsp; </p>
      <p>Dr. Elliott&rsquo;s academic and practice interests focus on using implementation science, systems science, and process evaluation methods to improve the health of vulnerable populations. She is particularly interested in adolescent and family access to health services, the intersection of mental health and juvenile justice, school health, academic-practice partnerships, and health policies at the local, state, and federal level. Dr. Elliott joined the department of Community Health Sciences as faculty in 2013, after teaching for four years in an adjunct capacity. Prior to her work in academe, she spent ten years in management within the health sector overseeing complex projects.  She received a BA in Psychology from Colby College, a MPH degree with dual concentrations in Social and Behavioral Sciences, and Maternal and Child Health from Boston University where she also completed her DrPH in Maternal and Child Health. </p>
    </div>
    <button class="accordion">Charvonne Holliday</button>
    <div class="panel"> <img src="../../images/charvonne-holliday.png" alt="Charvonne Holliday" class="right ppic" />
      <p>Charvonne N. Holliday, PhD, is trained in behavioral and community health, with research experience and public health practice related to women’s health and community-oriented approaches to positive change.</p>
      <p>Dr. Holliday is committed to understanding racial/ethnic disparities that persist in intimate partner violence (IPV) and women’s sexual/reproductive health by examining social and structural determinants of health. Current research includes examining racial/ethnic differences in reproductive coercion and women’s contraceptive decision making, mitigating barriers to help-seeking for survivors of IPV, and exploring innovative intervention strategies for male IPV perpetrators. I apply a mixed-methods approach, including participatory research methods like concept mapping.</p>
      <p>Current research includes examining racial/ethnic differences in reproductive coercion and women’s contraceptive decision making, mitigating barriers to help-seeking for survivors of IPV, and exploring innovative intervention strategies for male IPV perpetrators. Dr. Holliday applies a mixed-methods approach, including participatory research methods like concept mapping.</p>
    </div>
    <button class="accordion">Colleen Huebner</button>
    <div class="panel"> <img src="../../images/colleen-huebner.png" alt="Colleen Huebner" class="right ppic" />
      <p>Colleen Huebner’s background is in Developmental Psychology (PhD) and Epidemiology (MPH). She was a faculty member of the University of Washington’s Center of Excellence in MCH Education, Science and Practice for 25 years as a teacher, assistant director, director (Principal Investigator) and professor emeritus. Within the University of Washington’s School of Public Health, she taught courses in needs assessment, program planning and evaluation, health policy, and the historical and current influence of Title V on women, children and families in the U.S. She mentored the research of over 70 MPH students, PhD students and post-docs and helped guide many of their projects to peer-reviewed publication.</p>
      <p>Her own research focused on the design, implementation and evaluation of community- and clinic-based preventive intervention programs for young children and families in poverty including programs to prevent infant maltreatment, promote early language development, emergent literacy and protect children’s oral health. She was a member of several interdisciplinary research teams at the University and worked with numerous collaborators including families and practitioners in rural communities in Washington, Oregon, Colorado, and in Alaska Native villages; people working in public libraries, community health clinics, Head Start programs, early intervention and family centers in Seattle, Chicago, and in the Republic of the Marshall Islands. A common goal of Dr. Huebner’s research was to establish the evidence for effective, feasible policies and programs that support young children’s health and development and, in turn, disseminate those practices broadly to benefit all children and families in need. In acknowledgment of this work, she served as a Presidential Appointee to the U.S. National Commission on Libraries and Information Science (2003-2007).</p>
      <p>Dr. Huebner, along with colleagues in MCH academe, field-based public health and clinical practice, established the groundwork for several MCH resources of national scope including the MCH Leadership Competencies and the MCH Navigator. She was on the editorial board of the <em>Maternal and Child Health Journal</em> for many years and, in 2005, received the Loretta P. Lacey Academic Leadership Award of the Association of Teachers of Maternal and Child Heath.</p>
    </div>
    <button class="accordion">Russell Kirby</button>
    <div class="panel">
      <p><img src="../../images/Russell-Kirby.jpg" alt="Russell S. Kirby" class="right ppic" />Russell S. Kirby, Ph.D., M.S., F.A.C.E., Distinguished University Professor, Marrell Endowed Chair, and Faculty Strategic Area Lead for Population Health Science, University of South Florida</p>
      <p>Dr. Russell Kirby is a perinatal and pediatric epidemiologist trained in the social sciences, with a PhD in human geography (Wisconsin, 1981) and MS in preventive medicine-epidemiology (Wisconsin, 1991). Dr. Kirby worked at the state health agencies in Wisconsin and Arkansas, on the faculties of the Department of Pediatrics, University of Arkansas for Medical Sciences, and Department of Obstetrics and Gynecology, Milwaukee Clinical Campus, University of Wisconsin Medical School, and the School of Public Health, University of Alabama-Birmingham prior to joining the faculty of the University of South Florida in 2008.  He was elected Fellow in the American College of Epidemiology in 1996, and served as president in 2018-19. Dr. Kirby previously served as President of the National Birth Defects Prevention Network, the Wisconsin Association for Perinatal Care and the Arkansas Perinatal Association, Society for Pediatric and Perinatal Epidemiologic Research, and the Association of Teachers of Maternal and Child Health. </p>
      <p>Dr. Kirby has authored more than 300 peer-reviewed articles, with more than 500 different co-authors, and actively participates in the editorial process as a peer reviewer or editorial board member for numerous journals. While his research interests focus on the public health implications of health policies and programs, with special reference to perinatal and maternal/child health; population health informatics; and perinatal/pediatric studies in genetics, birth defects, and developmental disabilities, clinical research, study design and analysis, birth defects surveillance and epidemiology has been a major interest since the early 1980s.</p>
    </div>
    <button class="accordion">Michael Kramer</button>
    <div class="panel">
      <p><img src="../../images/michael-kramer.jpg" alt="Michael Kramer" class="right ppic" />Michael Kramer, PhD, MMSc, is a social epidemiologist, health disparities scholar, and the Director of the Emory Center of Excellence in Maternal and Child Health Education, Science, and Practice. He was also a HRSA MCHB trainee himself. His research seeks to advance theory for the social determinants of health, develop and implement novel methods for measuring and quantifying the biological embodiment of social experiences and environments, and advancing impactful science focusing on improving the health of women and children. His research has been supported by NIH, HRSA, CDC, and March of Dimes. </p>
      <p>Dr. Kramer's current projects focus on building the evidence base to inform social and community policies to eliminate disparities in severe maternal morbidity and mortality. He currently serves as the co-chair of the Georgia maternal mortality review committee.</p>
    </div>
    <button class="accordion">Lois McClosky</button>
    <div class="panel">
      <p><img src="../../images/Lois-McClosky.jpg" alt="Lois McCloskey" class="right ppic" />Lois McClosky, DrPH, began her public health career 30 years ago as an applied anthropologist and educator of community health workers in Nepal. The work inspired her lifelong concern with the health care of women and their infants, particularly in communities that are under-served. In both international and domestic settings, her work focuses on the disconnects between the lives of women and the health care systems meant to serve their needs across the life course and proven strategies for engaging and activating women to be full partners in their reproductive health care and planning. She is currently supported by the NICHD and NIDDK to study the barriers to follow-up testing and prevention for women with gestational diabetes, a harbinger of risk type 2 diabetes mellitus later in life. At BUSPH she serves as Associate Chair of the Department of Community Health Sciences, Co-Director of the MCH Certificate, and Director of the Center of Excellence in Maternal and Child Health, a Center dedicated to the education of a diverse MCH workforce, ready to lead. As an educator, she specializes in practice-based courses that engage students in the application of their skills and knowledge in real life organizations, addressing real life challenges. Currently she teaches &ldquo;Implementing Community Health Initiatives: A Field-based Course in Leadership and Consultation&rdquo; and &ldquo;Sexual and Reproductive Health Advocacy: From Rights to Justice.&rdquo;</p>
      <p> Dr. McClosky completed an MPH in population, family and international health and a DrPH in perinatal epidemiology and health services research at UCLA School of Public Health. Upon graduation, she co-founded the Institute for Urban Health Policy and Research for the Boston Department of Health and Hospitals and served as its Senior Research Scientist for 7 years before joining the faculty of Boston University. During her tenure at the Institute, she led research and community action initiatives designed to mobilize community residents, health professionals, academics, and policy-makers to eliminate racial disparities in infant death and pre-term birth. The findings led to fundamental changes in how perinatal health services are delivered to women of African descent in Boston. She directed the launch of a study abroad program, &ldquo;IHP: Health and Community&rdquo;, dedicated to comparative study of health, systems and culture in four countries. She co-founded the Women&rsquo;s Health Committee of the MCH Section of the American Public Health Association, is a member of the Association of Teachers of Maternal and Child Health, and serves on the peer review panels of the Women&rsquo;s Health Journal, the Maternal and Child Health Journal, the Journal of the Poor and Under-served, and Public Health Reports, BMC Health Services, and BMC Pregnancy and Birth. </p>
    </div>
    <button class="accordion">Cynthia Minkovitz</button>
    <div class="panel"> <img src="../../images/Cynthia-Minkovitz.jpg" alt="Cynthia Minkovitz" class="right ppic" />
      <p>Cynthia Minkovitz, MD, MPP, is the William H. Gates, Sr. Professor and Chair of the Department of Population, Family and Reproductive Health at Johns Hopkins Bloomberg School of Public Health, and a Professor of Pediatrics in the School of Medicine. Her research focuses on enhancing the quality of preventive services and understanding the impact of systems reforms on the health and well-being of children and families.</p>
      <p>Dr. Minkovitz serves on the Leadership Team for the Home Visiting Applied Research Collaborative (HARC).  HARC’s mission is to promote the use of innovative research methods to advance precision home visiting and to accelerate the integration of results into practice.   Dr. Minkovitz has led national and state evaluations including Healthy Steps for Young Children, the Dyson Community Pediatrics Training Initiative, and New Jersey Project LAUNCH.  She also co-led efforts to develop a framework to promote coordination in the early childhood system and collaborates on New Jersey’s Preschool Development Grant and Maryland’s Prenatal to Three Initiative.</p>
      <p>Dr. Minkovitz is Director of the Johns Hopkins Center of Excellence in MCH; she has led the MCH Postdoctoral Fellowship Program since 2015. Dr. Minkovitz has received numerous awards including the Academic Pediatric Association Research Award as well as institutional awards for excellence in teaching and mentoring.</p>
    </div>
    <button class="accordion">Terri Powell</button>
    <div class="panel">
      <p><img src="../../images/terri-powell.jpg" alt="Terri Powell" class="right ppic" />Terrinieka W. Powell, PhD, is an Associate Professor in the Department of Population, Family and Reproductive Health  at Johns Hopkins Bloomberg School of Public Health. She has an extensive history of using community-engaged approaches and working with community partners (e.g., churches, libraries and youth-oriented CBOs) to conduct research. She has expertise in adolescent health, qualitative methods, intervention development and implementation science. She has collaborated with institutions across several states to promote educational attainment as well as prevent teen pregnancy, HIV, and substance use among adolescents. She has over 40 publications and has been PI or Co-I on 10 externally funded grants that seek to improve the lives of vulnerable young people.</p>
    </div>
    <button class="accordion">William Sappenfield</button>
    <div class="panel">
      <p><img src="../../images/william-sappenfield.png" alt="William Sappenfield" class="right ppic" />William M. Sappenfield, MD, MPH, CPH is Professor and Director of the Chiles Center at the College of Public Health, University of South Florida. He also serves as Director of the Florida Perinatal Quality Collaborative (FPQC), a statewide multi-organizational effort to improve health and health care quality of mothers and infants.  As both a pediatrician and an epidemiologist, Dr. Sappenfield has 35 years of experience in epidemiological and public health research, teaching, and practice in maternal and child health at a community, state and national level. <br>
        <br>
        As a nationally recognized leader in the field of maternal and child health epidemiology, Dr. Sappenfield spent the first 22 years of his career as a CDC medical epidemiologist working on assignment with state and local public health agencies to enhance their capacity to use epidemiology, evaluation and research to improve the health of the women and children.  This includes being assigned to work directly in three state public health agencies as well as at CityMatCH, a national organization support MCH in urban health departments.  He completed his CDC career serving four years as Team Leader of the MCH Epidemiology Program directly responsible for the national MCH EPI effort including training, mentoring and supporting maternal and child health epidemiologists around the nation.  </p>
      <p>Upon retiring from the CDC and the U.S. Public Health Service, Dr. Sappenfield served six years at the Florida Department of Health as the State MCH Epidemiologist and as Unit Director for the MCH Practice and Analysis Unit. His responsibilities included leading the Department&rsquo;s research, epidemiology, evaluation and health data efforts to guide policies and programs for Florida mothers and children at a state and community level.  </p>
      <p>In recent years working at the Chiles Center, Dr. Sappenfield is one of the leader to develop the FPQC which has emerged as a multi-partner collaborative supporting hospitals and providers in improving the quality of health care provided to mothers and infants.  These efforts include reducing the rate on non-medially indicated early term deliveries, managing maternal hemorrhage at delivery, treating maternal hypertension in a timely fashion, promoting use on mother&rsquo;s own milk in the ICU, reducing primary cesareans, promoting access to immediate postpartum use of LARC, and improving the health care of mothers with opioid use disorder and their babies.  FPQC currently works with 86 Florida delivery hospitals that serve 86% of the state mothers and their newborns and has made measurable improvements in the state maternal and infant health outcomes as well as reduce health care costs.  </p>
      <p>Dr. Sappenfield&rsquo;s other significant maternal and child health contributions include:  early developments in the community-based fetal, infant and maternal mortality reviews, adapting an applied approach to investigating a community&rsquo;s infant mortality problem called &ldquo;Perinatal Periods of Risk,&rdquo; developing core state indicators for monitoring preconception health and MCH life course, and promoting best practices in maternal and child health epidemiology.  Dr. Sappenfield has received multiple awards including the 2003 National MCH Epidemiology Award for Outstanding Leadership, the 2012 Elaine Whitelaw National Volunteer Service Award by the March of Dimes Foundation, the 2014 MCH Bureau Director&rsquo;s Award from Health Resources and Services Administration, the 2016 John C. MacQueen Annual Lectureship Award from the Association of Maternal and Child Health Programs, the 2020 Health Care Hero Award from the Florida Alliance for Healthcare Value, and the 2020 Distinguished Service Award from the American College of Obstetrics and Gynecology.  As the Director, the FPQC was award the 2016 Sapphire Award Recognizing Excellence and Innovation in Community Health for an Organization.</p>
    </div>
    <button class="accordion">Ellen Schafer</button>
    <div class="panel"> <img src="../../images/ellen-schafer.jpg" alt="Ellen Schafer" class="right ppic" />
      <p>Dr. Ellen Schafer earned her Ph.D. in Public Health with an emphasis on  Community and Behavioral Health from the University of Iowa in 2015, and completed a two-year postdoctoral fellowship in Maternal and Child Health at the University of South Florida before coming to Boise State University in 2018. Schafer is a Master Certified Health Education Specialist and received her Masters of Public Health (MPH) in Community Health Education in 2006 from the University of Wisconsin La Crosse.</p>
      <p>Dr. Schafer teaches health promotion and education, and public health classes. Her professional health education experience includes working as a health and wellness specialist with the Greater Southern Tier Board of Cooperative Educational Services, funded by the New York State Tobacco Control Program. She worked with K-12 school districts in New York State to develop, implement, enforce, and evaluate tobacco-free campus policies and educational initiatives. In addition, Schafer worked at the University of Mississippi as the Assistant Director of Student Health for Health Promotion, where she directed and implemented all of the health education and promotion activities on campus for students and staff and participated on the advisory board for the University’s Collegiate Recovery Community.</p>
      <p>Dr. Schafer’s main research objective is to understand the mechanisms by which social context and social network influences are associated with health behaviors, and she typically applies these factors to studies of infant feeding and care.</p>
    </div>
    <button class="accordion">Martha Wingate</button>
    <div class="panel">
      <p><img src="../../images/martha-wingate.jpg" alt="Martha Wingate" class="right ppic" />Dr. Martha S. Wingate (DrPH, MPH, UAB; BS, Birmingham-Southern College) is a Professor in the Department of Health Care Organization and Policy. She teaches courses in public health systems, maternal and child health, leadership, and perinatal health issues. Dr. Wingate serves as the Director of the Maternal and Child Health (MCH) Policy and Leadership Concentration. She also serves as the Director of the HRSA-funded Center of Excellence in MCH Education, Science, and Practice.<br>
        <br>
        She has published in a number of peer-reviewed journals, including American Journal of Public Health, Social Science and Medicine, and American Journal of Obstetrics and Gynecology and is co-author of a textbook on perinatal epidemiology. Her work focuses on preterm birth, fetal and infant mortality, racial and ethnic disparities in birth outcomes, and health policies related to pregnancy and infant health. She is engaged in technical assistance to the MCH workforce at the local, state, and national levels.</p>
    </div>
  </div>
</div>
</div>
<?php include('../../incl/footer.html'); ?>
