<?php 
$section = 'resources';
$page = 'links';
$page_title = "MCH Sites &amp; Links";
include ('../incl/header.html');
?>

<div class="container" style="margin-top: 2rem; margin-bottom: 2rem;">
  <?php include('../incl/leftnav.html'); ?>
  <div class="nine columns">
    <?php include('../incl/title.html'); ?>
    <p><img src="../images/www-bar.jpg" alt="MCH Sites and Links" width="300" height="201" class="right border" />The MCH Navigator has collected links to projects, organizations, associations, and federal agencies that provide trainings and materials focused on MCH and leadership to augment learning opportunities found on this site. For a list of websites that serve as gateways to online learning opportunities, see the <a href="sites.php">Training Sites</a> page.</p>
    <h2><i class="icon mch-map4" aria-hidden="true"></i> Table of Contents</h2>
    <ul>
      <li><a href="#leadership">MCH and Leadership</a></li>
      <li><a href="#mch">Resources on MCH Topics</a></li>
      <li><a href="#federal">Federal Agencies and Resources</a></li>
      <li><a href="#student">Student Associations and Programs</a></li>
      <li><a href="#professional">Professional Associations</a></li>
    </ul>
    <p>These links have been evaluated for the usefulness, reliability, and timeliness of the MCH information they present, and the ease with which visitors can access information and navigate in them. This list is not intended to be comprehensive; rather, it offers a sample of quality sites that are useful starting points for those interested in MCH topics. </p>
    <h2><a name="leadership" id="leadership"></a><i class="icon mch-cubes" aria-hidden="true"></i> MCH and Leadership</h2>
    <p><img src="../images/learn-lead.jpg" alt="Learn Lead" width="250" height="166" class="right border" />For more structured trainings, see the <a href="../trainings/topics.php">Topics, Primers, and Bundles</a> page or <a href="../trainings/search.php">Search for Trainings</a> by MCH Leadership Competency in the training database.</p>
    <ul>
      <li><a href="../documents/AMCHP-Senior-Managers-Guide-Final-6-15.pdf">Leading State Maternal and Child Health: A Guide for Senior Managers</a> (2015) provides information and resources for senior managers  responsible for the oversight or management of all or part of the MCH Services Block Grant. Titles, duties, and scopes of responsibility for family health related federal and state programs vary between agencies and states, but this guide was written to be adaptable to various situations regardless of  specific position titles or responsibilities. (PDF manual. Association of Maternal and Child Health Programs).</li>
      <li><a href="https://mchb.hrsa.gov/about-us/timeline">MCH Timeline: History, Legacy and Resources for Education and Practice</a> (2011) traces the history of MCH in the U.S., provides in-depth modules on topics such as MCH 101, MCH Systems of Care, Infant Mortality and MCH Performance and Accountability, and allows you to search for topical areas of interest to you. New staff orientation is highlighted. (Interactive website. U.S. Maternal and Child Health Bureau).</li>
      <li><a href="https://www.mchnavigator.org/trainings/competencies.php">MCH Leadership Competencies</a> (2023) defines MCH leadership competencies in 12 areas and provides information about educational experiences, additional reading and assessment tools for each competency area. (Self-paced learning website. U.S. Maternal and Child Health Bureau).</li>
      <li><a href="https://www.powershow.com/view1/1e5f82-ZDc1Z/Leading_by_Example_Modeling_the_Future_of_MCH_powerpoint_ppt_presentation?varnishcache=1#google_vignette">Leading By Example: Modeling the Future for MCH</a> (2007) provides short video clips on leadership and management in the MCH setting. Excerpts from a lecture by Donna Petersen, MHS, ScD, Dean, College of Public Health, University of South Florida, from the October 2007 HRSA MCHB Federal/State Partnership Meeting. (Video clips. Johns Hopkins Bloomberg School of Public Health).</li>
      <li><a href="http://www.uic.edu/sph/mch/continuing_education.htm">Authentic Leadership: A Coach-Approach to Inspired Public Health Leadership</a> (ongoing) is a 6-month distance based program that takes place over the phone and through an online discussion board. It begins twice yearly in January and July. This program builds emotional intelligence and develops authentic leadership capacity by focusing on strengths, values-based decision-making and goal-setting, authenticity, vulnerability, courage/risk-taking, and self-care/happiness as they relate to leadership. The MCH program partners with various members of the UIC community and other external partners to host events that address MCH issues or provide professional/career development opportunities to public health professionals. (Distance-based program. University of Illinois at Chicago, School of Public Health, Maternal and Child Health Program).</li>
    </ul>
    <a name="mch" id="mch"></a>
    <h2><i class="icon mch-book" aria-hidden="true"></i> Resources on MCH Topics</h2>
    <ul>
      <li><img src="../images/NCEMCH-vertical.jpg" alt="NCEMCH" width="500" height="333" class="right border" />The <a href="https://www.mchlibrary.org">MCH Digital Library</a> at the <a href="https://www.ncemch.org">National Center for Education in Maternal and Child Health</a> serves as the companion to the MCH Navigator by providing access to online materials relevant to the needs of the MCH workforce. Access resources such as lifecourse and social determinants, racial and ethnic disparities in health, evaluation, and more.
        <ul>
          <li><a href="https://www.mchlibrary.org/toolkits/">Title V Toolkits</a>. Toolkits provide access to resources that can be used in a concerted approach to address specific public health issues.</li>
          <li><a href="https://www.mchlibrary.org/professionals/">Professional Resource Guides and Briefs</a>. Resource guides (including knowledge paths) and briefs provide access to recent, high quality resources and tools to learn more about the topic, conduct further research, locate trainings, develop programs, and stay abreast of new developments.</li>
          <li><a href="https://www.mchlibrary.org/families/">Family Resources</a>. Family Resource Briefs list websites, online directories, and other resources for families and those who support them.</li>
          <li><a href="https://www.mchlibrary.org/schools/">School Resource Briefs</a>. School resource briefs list websites, online directories, and other resources for developing and evaluating programs and for educating students and their families, teachers, and school staff.</li>
        </ul>
      </li>
    </ul>
    <h2><a name="federal" id="federal"></a><i class="icon mch-bookmark" aria-hidden="true"></i> Federal Agencies and Resources</h2>
    <ul>
      <li><a href="https://www.acf.hhs.gov/">Administration for Children and Families (ACF)</a>. Describes ACF's programs and services that promote the economic and social well-being of families and children. Resources include research reports and statistics about child care and child welfare. ACF is part of the Department of Health and Human Services (DHHS).</li>
      <li><a href="http://www.hrsa.gov/about/organization/bureaus/bphc/index.html">Bureau of Primary Health Care (BPHC)</a>.  Contains program information and publications about primary health care for the underserved. Offers several online databases with information about drug pricing, health professional shortage areas, primary care practice areas, BPHC-supported health centers, medically underserved areas, and successful program models. </li>
      <li><a href="http://www.cdc.gov/">Centers for Disease Control and Prevention (CDC)</a>.  Offers a wealth of information for health professionals, policymakers, and consumers to promote health and quality of life by preventing and controlling disease, injury, and disability. Resources are provided in English and Spanish and include publications, databases, and other online products, such as CDC Wonder.</li>
      <li><a href="http://cms.gov/">Centers for Medicare &amp; Medicaid Services (CMS)</a>.  Offers program information, publications, forms, and data about Medicare, Medicaid, the State Children's Health Insurance Program (SCHIP), and the Health Insurance Portability and Accountability Act (HIPAA). </li>
      <li><a href="http://www.nichd.nih.gov/">Eunice Kennedy Shriver National Institute of Child Health and Human Development (NICHD)</a>.  Contains resources for health professionals, researchers, and consumers that include publications related to NICHD research, information about the Milk Matters and Back to Sleep public health campaigns, news releases, and funding and research information.</li>
      <li><a href="http://www.hrsa.gov/">Health Resources and Services Administration (HRSA)</a>.  Describes its key program areas and grant programs aimed at improving the nation's health by expanding access to comprehensive, quality health care for all Americans. Resources include publications, data and statistics, and information about events and initiatives. The Maternal and Child Health Bureau is part of HRSA, which is part of the <a href="http://www.dhhs.gov/">Department of Health and Human Services (DHHS)</a>.</li>
      <li><a href="https://www.healthypeople.gov/2020/">HealthyPeople.gov</a>.  Describes this national health promotion and disease prevention initiative created by a broad coalition of experts from many sectors to improve the health of all Americans, eliminate disparities in health, and improve years and quality of healthy life. Includes background information on the initiative; the complete text (online and searchable), Healthy People 2010: Understanding and improving health (2nd ed.) (2000); data and statistics, a list of Healthy People partners and related sites; and other publications.</li>
      <li><a href="http://www.mchb.hrsa.gov/">Maternal and Child Health Bureau (MCHB)</a>.  Describes MCHB's projects and initiatives on behalf of America's women, infants, children, adolescents, and their families. Programs include the Title V block grant to states. Information about funding opportunities, data, and publications is also provided. MCHB is part of the <a href="http://www.hrsa.gov/">Health Resources and Services Administration (HRSA)</a>.</li>
      <li><a href="http://mchb.hrsa.gov/">Maternal and Child Health Training Program</a>. Provides information about MCHB's  Division of Maternal and Child Health Workforce Development (DMCHWD) and resources for it's grantees and trainees, including grant information, details on impact and reporting, DMCHWD programs, and details on Title V programs.
        <ul>
          <li><a href="https://mchb.hrsa.gov/programs-impact/focus-areas/building-mch-leaders-mch-workforce/leadership-competencies">MCH Leadership Competencies</a>. Outlines the 12 leadership competencies and provides a forum for conversation about how they can be incorporated into training.</li>
          <li><a href="http://mchb.hrsa.gov/about/timeline/index.asp">MCH Timeline</a>. Traces the history of MCH in the U.S., provides in-depth modules on topics such as MCH 101, MCH Systems of Care, Infant Mortality and MCH Performance and Accountability, and allows users to search for topical areas of interest.</li>
        </ul>
      </li>
      <li><a href="http://nhsc.hrsa.gov/">National Health Service Corps</a>. Offers loan repayment assistance to support qualified health care providers who choose to bring their skills where they’re most needed.</li>
      <li><a href="http://www.nimhd.nih.gov/">National Institute on Minority Health and Health Disparities (NIMHD)</a>.  Contains the National Institutes of Health strategic research plan and budget to reduce and ultimately eliminate health disparities. Also includes grant and conference information. </li>
      <li><a href="https://minorityhealth.hhs.gov/omh/browse.aspx?lvl=1&lvlid=3">Office of Minority Health Resource Center (OMHRC)</a>.  Offers links to publications, programs, funding databases, conference information, and news updates on minority health-related topics. OMHRC is part of the <a href="https://minorityhealth.hhs.gov">Office of Minority Health</a>.</li>
      <li><a href="http://www.surgeongeneral.gov/index.html">Office of the Surgeon General</a>.  Includes reports, calls to action, and conference proceedings about important public health issues. Also describes the duties of the Surgeon General and a history of the office. </li>
    </ul>
    <h2><a name="student" id="student"></a><i class="icon mch-graduation-cap-1" aria-hidden="true"></i> Student Associations and Programs</h2>
    <ul>
      <li><a href="https://www.amsa.org">American Medical Student Association</a>. Student-governed, national organization committed to representing the concerns of physicians-in-training. AMSA members are medical students, premedical students, interns, residents and practicing physicians.</li>
      <li><a href="http://www.apha.org/membergroups/students/">American Public Health Association Student Assembly</a>. The nation's largest student-led organization dedicated to furthering the development of students, the next generation of professionals in public health and health-related disciplines. APHA-SA represents and serves students of public health and other health-related disciplines by connecting individuals who are interested in working together on public health and student-related issues.</li>
      <li><a href="http://www.asdanet.org/">American Student Dental Association</a>. Protects and advances the rights, interests and welfare of dental students while developing great leaders in dentistry.</li>
      <li><a href="https://apamsa.org">Asian Pacific American Medical Students Association</a>. Addresses those issues important to Asian-American medical students by promoting the health and well-being of the Asian community as well as in helping all health care workers who work with these communities understand how to care for the Asian patient in a culturally sensitive manner.</li>
      <li><a href="http://www.anamstudents.org/">Association of Native American Medical Students</a>. Represents Native American graduate health profession students throughout the U.S. and Canada.  ANAMS is comprised of Native American students enrolled in medical school or in the allied health professions: Dentistry, Veterinary, Optometry, Podiatry, Pharmacy, and Public Health.</li>
      <li><a href="https://bhw.hrsa.gov/funding">HRSA Loans and Scholarships</a>. Increases the diversity of the health professions workforce and the number of providers working in underserved communities, by providing HRSA funds to accredited U.S. health professions schools.</li>
      <li><a href="http://www.nsna.org/">National Student Nurses Association</a>. Mentors students preparing for initial licensure as registered nurses, and  conveys the standards, ethics, and skills that students will need as responsible and accountable leaders and members of the profession.</li>
    
      <li><a href="http://lmsa.net/">Latino Medical Students Association</a>. Represents, supports, educates, and unifies US Latino(a) medical students. </li>
      <li><a href="http://www.snma.org/">Student National Medical Association</a>. Focuses on the needs and concerns of medical students of color, the SNMA has provided 50 years of advocacy and service to underserved communities and medical students.</li>
        <li><a href="https://www.iadr.org/membership/communities/groups-networks/student-training-and-research-star-network">Student Training and Research (STAR) Network, American Association for Dental Research</a>. Fosters an environment in every dental school whereby students interested in enriching their dental education through research are encouraged to do so. </li>
    </ul>
    <h2><a name="professional" id="professional"></a><i class="icon mch-building-o" aria-hidden="true"></i> Professional Associations</h2>
    <ul>
      <li><a href="https://www.academicpeds.org">Academic Pediatric Association (APA)</a>. Educational guidelines for pediatric residency programs; information about APA's research, special interest groups, meetings, newsletter, and journal.</li>
      <li> <a href="http://www.aacap.org">American Academy of Child and Adolescent Psychiatry (AACAP)</a>. Resources for families, medical students and residents, and practitioners about developmental, behavioral, emotional, and mental disorders affecting children and adolescents. Some family materials are available in Arabic, Hebrew, Icelandic, Malaysian, Polish, Spanish, and Urdu.  </li>
      <li> <a href="http://www.aafp.org">American Academy of Family Physicians (AAFP)</a>. Professional resources including clinical and research, running a practice, policy and advocacy, training, and careers. Information on public health issues, immunization, disaster preparedness, genomics, and Medicare Part D drug benefits. </li>
      <li> <a href="http://www.aapd.org">American Academy of Pediatric Dentistry (AAPD)</a>. Guidelines, journals, brochures, and other resources  for health professionals and parents about improving oral health for infants, children, and adolescents, including those with special health care needs.  </li>
      <li> <a href="http://www.aap.org">American Academy of Pediatrics (AAP)</a>. Resources for parents and professionals regarding the physical, mental, and social health of infants, children, adolescents, and young adults, as well as information about AAP's advocacy work, research, publications, membership, and meetings. </li>
      <li> <a href="http://www.aapa.org">American Academy of Physician Assistants (AAPA)</a>. Information about physician assistant programs and the physician assistant profession. </li>
      <li> <a href="http://www.midwife.org">American College of Nurse-Midwives (ACNM)</a>. Information on finding and becoming a midwife, continuing education, practice resources, publications and research, consumer information.  </li>
      <li> <a href="http://www.acog.org">American College of Obstetricians and Gynecologists (ACOG)</a>. Resources for advocacy, professional education, practice management, and women's issues. Quick guides to Web information on selected topics. </li>
      <li> <a href="http://www.ada.org">American Dental Association (ADA)</a>. Activities for kids, classroom activity resources, A-Z oral health topics, directory of member dentists, and professional resources. </li>
      <li> <a href="http://www.aha.org">American Hospital Association (AHA)</a>. Resources on advocacy, health systems issues, research and trends, news. Links for consumers and health leaders.  </li>
      <li> <a href="http://www.ama-assn.org">American Medical Association (AMA)</a>. Resources for physicians and consumers on a variety of health topics affecting families. Also contains information about AMA's policy and advocacy work, accreditation, education opportunities, products, services, and publications. </li>
      <li> <a href="http://www.amwa-doc.org">American Medical Women's Association (AMWA)</a>. Professional resources on advocacy, career development, meetings, and a professional journal. </li>
      <li> <a href="http://www.apa.org">American Psychological Association (APA)</a>. Resources for health professionals, educators, and parents about child, adolescent, and family mental health. </li>
      <li> <a href="http://www.apha.org">American Public Health Association (APHA)</a>. Resources on advocacy and on public health issues such as health insurance, disaster preparedness, the environment, and school-based health care. Annual conference and bookstore.  </li>
      <li> <a href="http://www.ashaweb.org">American School Health Association (ASHA)</a>. Describes an optimal school health program and offers information about its membership, conferences, and publications. </li>
      <li> <a href="http://www.amchp.org">Association of Maternal and Child Health Programs (AMCHP)</a>. Advocacy resources on federally-funded maternal and child health programs and links to resources on current MCH topics from adolescent health through workforce development. Conferences, webinars, and publications.  </li>
      <li> <a href="http://www.aspph.org">Association of Schools and Programs of Public Health (ASPPH)</a>. Definition of public health, list of member schools, curriculum and public health practice resources, and advocacy materials. </li>
      <li> <a href="http://www.astho.org">Association of State and Territorial Health Officials (ASTHO)</a>. Program information, publications, and other resources for public health professionals on topics such as access to health care, immunizations, and environmental health. Provides a list of state health officials and links to state health departments.  </li>
      <li><a href="../academics/atmch/index.php">Association of Teachers of Maternal and Child Health (ATMCH)</a>. Offers an interdisciplinary forum through which MCH faculty from schools of public health and other institutions of higher learning can share the knowledge, ideas, and skills essential to educating students, advancing MCH research, and applying research results to MCH policies, programs, and services.
        <ul>
          <li><a href="../academics/atmch/teaching-learning-resources/index.php">Teaching &amp; Learning Resources</a>  (formerly MCH Syllabi Project)</li>
        </ul>
      </li>
      <li> <a href="http://www.citymatch.org">CityMatCH</a>. Resources about urban maternal and child health (MCH) issues. Initiatives include the Perinatal Periods of Risk (PPOR) collaborative and the MCH Life Course Toolbox. CityMatCH is a national membership organization for city and county health departments' MCH programs and leaders representing urban communities in the United States. </li>
      <li><a href="http://ceph.org/">Council on Education for Public Health</a>. An independent agency recognized by the U.S. Department of Education to accredit schools of public health and public health programs outside schools of public health. </li>
      <li><a href="https://nashp.org/">National Academy for State Health Policy (NASHP)</a>. Program, research, and conference information; publications; and news about state health policy and practice. Topics include children's health insurance, early childhood health and development, oral health, and others  .</li>
      <li><a href="http://www.nationalahec.org/">National Area Health Education Center Organization</a>. Supports and advances the Area Health Education Center (AHEC) Network to improve health by leading the nation in recruitment, training and retention of a diverse health work force for underserved communities.</li>
      <li> <a href="https://www.naccho.org/">National Association of County and City Health Officials  (NACCHO)</a>. Program information, publications, assessment tools, advocacy, and other resources for local public health officials on topics such as health reform implementation and radiation and nuclear preparedness. </li>
      <li> <a href="http://www.napnap.org">National Association of Pediatric Nurse Practitioners (NAPNAP)</a>. Resources on advocacy and legislation, continuing education, programs and initiatives, practice resources, patient education, and research updates.  </li>
      <li> <a href="http://www.nasn.org">National Association of School Nurses (NASN)</a>. Resources on continuing education, professional development, policy and advocacy, and research. Links to educational campaigns and other resources on topics of interest to school nurses such as childhood obesity, promoting non-violence, environmental health, and meningitis. </li>
      <li> <a href="https://www.ncsl.org/">National Conference of State Legislatures (NCSL)</a>. State legislative information, policy analysis, publications, and news about current issues affecting states. </li>
      <li> <a href="http://www.nga.org">National Governors Association (NGA)</a>. State and federal legislative news and policy analysis on issues affecting states. Issue briefs and other publications on maternal and child health topics including health reform implementation, early childhood care and education, and obesity prevention. </li>
      <li> <a href="http://www.nmanet.org">National Medical Association (NMA)</a>. Resources for professionals including a journal, calendar of events, and the Cobb Health Institute which conducts data-driven research and makes policy recommendations. Consumer resources on diabetes education, smoking cessation, HIV/AIDS prevention and other topics.  </li>
      <li> <a href="http://www.nsba.org">National School Boards Association (NSBA)</a>. Legislative issues, advocacy, promising school district practices, and resources on school health and school law.</li>
      <li> <a href="https://www.adolescenthealth.org/Home.aspx">Society for Adolescent Health and Medicine (SAHM)</a>. Resources for professionals including position papers, a list service, continuing education, and annual conferences. Links to sites for professionals and youth. </li>
      <li><a href="http://www.sophe.org/">Society for Public Health Education (SOPHE)</a>. Promotes healthy behaviors, healthy communities, and healthy environments through its membership, its network of local chapters, and its numerous partnerships with other organizations.</li>
    </ul>
    <p>&nbsp;</p>
    <hr />
    <p><strong>MCH Sites and Links</strong><br />
      December 2013; Updated July 2016<br />
      <strong>Author: </strong>John Richards, M.A., AITP, MCH Navigator<br />
      <strong>Reviewer:</strong> Olivia Pickett, M.L.S., M.A., NCEMCH</p>
  </div>
</div>
<?php include('../incl/footer.html'); ?>