<?php 
$section = 'trainings';
$page = 'training';
$page_title = "Training Spotlight";
include ('../incl/header.html');
?>
<div class="container" style="margin-top: 2rem; margin-bottom: 2rem;">
<?php include('../incl/leftnav.html'); ?>
<div class="nine columns">
<?php include('../incl/title.html'); ?>	
			<h2>Navigating Your Way through Health Reform and the ACA</h2>
            <p><strong><img src="../images/Affordable-Care-Act-300x200.jpg" width="300" height="200" alt="ACA" class="right border" /></strong>As provisions of the Patient Protection and Affordable Care Act (ACA) are being enacted,  there is a pressing need for materials relevant to the MCH workforce. This &ldquo;Just-In-Time&rdquo; Spotlight presents trainings and resources to assist the Title V staff and grantees with understanding and implementing the ACA.  </p>
            <p>Check back often as new training materials are added as they are developed and identified. We also invite you to <a href="mailto:mchnavigator@ncemch.org">submit</a> trainings or resources that you feel are relevant.</p>
            <h2>Table of Contents</h2>
            <ul>
              <li><a href="#intro">Introduction and Spotlight Overview</a> </li>
              <li><a href="#youtube">YouTube Videos</a></li>
              <li><a href="#webinars">Webinars and Presentations</a></li>
              <li><a href="#states">MCH ACA in Practice: Selected State Trainings and Examples in Title V Programs</a></li>
              <li><a href="#summaries">Quick Reference Summaries to Facilitate Training</a></li>
              <li><a href="#tools">Tools to Augment Training</a></li>
              <li><a href="#additional">Additional ACA Resources</a></li>
            </ul>
            <hr />
            <h2><a name="intro" id="intro"></a>Introduction and Spotlight Overview</h2>
            <p>Children and adolescents who are uninsured have decreased access to well-child care, immunizations, dental services, and prescription medications. The ACA, signed into law on March 23, 2010, is intended to expand access, reduce cost, and improve the quality of health for all Americans, including the MCH community. Components of the ACA are designed specifically to meet the needs of children and youth, including improved access to covered services, provision of age-appropriate benefits, and increased health insurance coverage. In addition, the ACA provides support to strengthen the pediatric workforce, a structure for state MCH, Medicaid, and Children's Health Insurance Program (CHIP) staff, and a plan to improve pediatrician payment rates.</p>
            <p>Included in this Spotlight are short online videos, quick reference summaries, and presentations that illuminate basic ACA concepts and outline step-by-step requirements for ACA implementation. Examples of the ACA in practice, state-specific data, and resource organizations are included for those who wish to explore the topic in more depth. The Spotlight highlights trainings of different modalities (reading, viewable presentations, web tutorials) to provide multiple avenues to learning. </p>
            <hr />
            <h2><a name="youtube" id="youtube"></a>YouTube Videos</h2>
            <ul>
              <li><a href="http://www.youtube.com/watch?v=R-tB9jdfMqA">The ABCs of ACOs for MCH</a> (2013) explores key considerations of the ACA for MCH populations, the role of public health in accountable care organization (ACO) implementation, and efforts to implement ACOs that have a focus on pediatric populations with an emphasis on children with special health care needs (CSHCN). (90 minute online training. AMCHP).</li>
              <li><a href="http://www.youtube.com/watch?v=AWnhFpplrkY">Continuing the Conversation: The Affordable Care Act after the Supreme Court Ruling</a> (2012)  reviews  the key provisions of the ACA, presents implications of the June Supreme Court ruling for MCH populations, and conducts an in-depth discussion of the Medicaid expansion and health insurance exchange establishment. (YouTube video series. AMCHP and members).</li>
              <li><a href="http://www.youtube.com/watch?v=vmdbllWOOzs">Health Reform Explained Video: Health Reform Hits Main Street</a> (2010) explains and illustrates health care reform and the Affordable Care Act for those who need to start at the beginning. (9 minute video. Henry J. Kaiser Family Foundation)</li>
              <li><a href="http://www.youtube.com/HealthCareGov">HealthCare.gov YouTube Channel</a> (2013) provides over 30 videos that are appropriate to share with families in explaining the ACA.</li>
              <li><a href="http://www.youtube.com/watch?v=zsqu_Ce8qec&amp;feature=youtu.be">Training: Understanding the Health Insurance Marketplace</a> (2013) provides an overview of how the Health Insurance Marketplace works, what it means for consumers and individuals, who is eligible to enroll, and how programs for people with limited incomes work. (46 minute video.  Health Insurance Marketplace, Centers for Medicare &amp; Medicaid Services (CMS)).</li>
              <li><a href="http://www.rwjf.org/en/about-rwjf/newsroom/newsroom-content/2011/10/video-vocab-understanding-the-affordable-care-act.html">Video Vocab: Understanding the Affordable Care Act</a> (2011-2013) explains concepts of health reform through  a series of short infographic videos. (Series of 1-2 minute videos. Robert Wood Johnson Foundation).</li>
              <li><a href="http://www.youtube.com/watch?v=JZkk6ueZt-U">The YouToons Get Ready for Obamacare</a> (2013) presents a summary of the ACA's changes that will begin in 2014 in language that most health consumers can understand. (7 minute video. Henry J. Kaiser Kaiser Family Foundation). </li>
            </ul>
            <hr />
            <h2><a name="webinars" id="webinars"></a>Webinars and Presentations</h2>
            <ul>
              <li><a href="https://cc.readytalk.com/cc/playback/Playback.do?id=40r3hs">ACA Delivery Reforms and Public Health: What's the Connection?</a> (2013) includes presentation slides presenting &quot;ACA 101&quot; and questions for the public health to consider as health reform is implemented. (90 minute archived webinar. American Public Health Association (APHA)). Also of note is APHA's <a href="http://www.apha.org/topics-and-issues/health-reform/health-reform-resources">Health Reform Resources</a> page.</li>
              <li><a href="https://sas.elluminate.com/site/external/launch/nativeplayback.jnlp?psid=2013-11-07.1325.M.CFB27668D744E78BE47E0942DA3212.vcr">Assessing the Potential Impact of the Affordable Care Act on Uninsured Community Health Center Patients: A Nationwide and State-by-State Analysis</a>. (2013) includes data on individuals and costs for opt-out states as they relate to community health centers. (Archived webinar. Clinical Directors Network).</li>
              <li><a href="http://www.hdwg.org/catalyst/news/2011-12-03/1">Children and the Medicaid Health Home State Plan Option</a> (2011) presents a panel of experts on medical home implementation and federal Medicaid and Title V representatives to help answer questions about the funding of care coordination activities for children and youth with special health care needs under health care reform. (Archived webinar. AMCHP and the Catalyst Center).            </li>
              <li><a href="http://www.enrollamerica.org/resources/webinars/making-enrollment-easer/">Making Enrollment Easier: New Guidance from CMS</a> (2013) presents experts from the Centers for Medicare and Medicaid Services (CMS) and the Center for Budget and Policy Priorities (CBPP) outlines five strategies that are available to all states to automate and streamline enrollment. (54 minute archived webinar. Enroll America).</li>
              <li><a href="http://www.amchp.org/Policy-Advocacy/health-reform/Documents/Recording.mp4">Optimizing Health Reform to Integrate Service Delivery Systems for Women, Children and their Families</a> (2011) highlights the efforts of state Title V maternal and child health programs and their partners to integrate health care service delivery systems.&nbsp;<a href="http://www.amchp.org/Policy-Advocacy/health-reform/Documents/10-12-2011WebinarSlides (2).pdf">Copies of the slides</a> are also available. (MP4 recording of archived webinar. AMCHP in partnership and supported by The Commonwealth Fund).</li>
            </ul>
            <hr />
            <h2><a name="states" id="states"></a>MCH ACA in Practice: Selected State Trainings and Examples  in Title V Programs</h2>
            <ul>
              <li>
                <a href="http://d7e817ce8ea0a6e155d8-d0cbe0fafd32161b2f46485a01bd72b1.r97.cf1.rackcdn.com/ACAOutreachRuralDiverse_04-30-2015.mp4">ACA Outreach to Rural and Diverse Populations</a>. The Catalyst Center discussed their research and findings related to inequities in health care coverage, especially for CYSHCN, and family leaders Lisa Sanderson (SD) and Donene Feist (ND) shared their experiences and strategies used in their states. These family leader speakers represent states with different experiences around Medicaid expansion – ND in which Medicaid expansion occurred and SD in which it did not. Family Voices of North Dakota serve as Navigators in their state, for those interested in hearing more about that experience, while South Dakota Parent Connection has ACA outreach strategies and examples to share as a non-navigator organization.  <a href="http://www.fv-ncfpp.org/files/4614/3222/6777/4.30.15_Webinar_Slides_ACAOutreach-r.compressed.pdf" title="ACA Outreach to Rural and Diverse Populations" target="_blank">Presentation slides</a>
</li>
              <li><a href="http://www.albany.edu/sph/cphce/phl_1012.shtml">The Affordable Care Act and Public Health in New York State: Health Benefits, Medicaid Expansion, and the Prevention Agenda</a> (2012) describes the Health Benefit Exchange in New York, how it will affect benefits, and the eventual effect on health promotion and disease prevention. Continuing education credits are available. (46 minute webcast. School of Public Health, University at Albany, State University of New York).</li>
              <li><a href="http://www.youtube.com/watch?v=7v18prVxXKo">The Affordable Care Act: Mandates, Exchanges, Medicaid... and All That</a> (2013)  describes what an exchange is supposed to do and what roles the states have in the default options. (90 minute YouTube video. Alabama Public Health Training Center in partnership with the Alabama Department of Public Health).</li>
              <li><a href="http://nefhealthystart.org/presentation-the-impact-of-the-aca-on-mch/">The Affordable Care Act's Impact on Maternal and Child Health</a> (2013) discusses the importance of the ACA, what it means for Florida, reforms currently in place, how the ACA will affect racial and ethnic disparities in health and pregnant women, the Health Insurance Marketplace, and essential health benefits. (PowerPoint training. Healthy Start Coalition of Manatee County).</li>
              <li>The Commonwealth Fund State Medicaid Case Studies detail innovations being undertaken by selected states to improve quality and efficiency in their Medicaid programs and how Medicaid can work with Title V programs to implement the ACA:
                <ul>
                  <li><a href="http://www.commonwealthfund.org/Publications/Case-Studies/2013/Mar/Aligning-Incentives-in-Medicaid.aspx">Aligning Incentives in Medicaid: How Colorado, Minnesota, and Vermont Are Reforming Care Delivery and Payment to Improve Health and Lower Costs</a></li>
                  <li><a href="http://www.commonwealthfund.org/Innovations/Case-Studies/2013/Mar/Minnesota-Medicaid.aspx">Health Care Payment and Delivery Reform in Minnesota Medicaid</a></li>
                  <li><a  href="http://www.commonwealthfund.org/Publications/Case-Studies/2013/Mar/Vermont-Medicaid-Payment.aspx">Medicaid Is One of Multiple Payers in Vermont&rsquo;s Health Care Reforms</a></li>
                  <li><a href="http://www.commonwealthfund.org/Publications/Case-Studies/2013/Mar/Colorado-Medicaid-Payment.aspx">Medicaid Payment and Delivery Reform in Colorado: ACOs at the Regional Level</a></li>
                </ul>
              </li>
              <li><a href="https://familyvoices.adobeconnect.com/p9anz5gmeyu/?launcher=false&fcsContent=true&pbMode=normal">F2Fs [Families-To-Families] Moving Forward with Healthcare Reform</a>. Family leaders shared resources and activities for helping families and professionals understand and navigate the ACA.
              Jennifer Akers of Family Voices Indiana highlighted resources created by Family Voices of Indiana, including an online ACA guide, and information dissemination strategies. Debbie Gilbert and Sondra Gilbert of the Kentucky F2F, Kentucky Commission for Children with Special Health Care Needs, shared their experience serving as enrollment assistors, or Kynectors, for children and families. Faye Manaster, Family Voices of Illinois, shared information about their annual Update on Health Care Reform for Children with Special Needs conference, now in its 6th year. Beth Dworetzky of the Catalyst Center and Janis Guerney, Family Voices Policy Co-Director, shared any relevant trend updates and responded to  participating F2Fs (presenters and participants) about what&rsquo;s going on for F2Fs and families related to health care reform. <a href="http://www.fv-ncfpp.org/files/5414/3222/8220/F2FsMovingForwardACA.pdf">Presentation slides</a>.              </li>
              <li><a href="http://www.urban.org/events/maximizing-enrollment-under-aca-lessons-states">Maximizing Enrollment Under the ACA: Lessons from the States</a> (2013) shares lessons learned that may be useful for state and federal policymakers as ACA implementation moves forward. Panelists  highlight state innovations that make enrollment faster, more efficient, and more effective, and  define realistic expectations for participation levels under the ACA. (90 minute video lecture. Urban Institute).</li>
              <li><a href="http://consumersforhealthcare.org/blog/aca-blog">Michigan Consumers for HealthCare Blog</a>, these post on the ACA address how it is being implemented in Michigan.</li>
              <li><a href="http://kff.org/medicaid/event/event-preparing-for-outreach-and-enrollment-under-the-affordable-care-act-lessons-from-the-states/">Preparing for Outreach and Enrollment under the Affordable Care Act: Lessons from the States</a> (2013) examines the lessons, challenges and successes of three leading states -- Maryland, Nevada and Oregon -- in effective outreach and enrollment efforts. (Video Conference. The Henry J. Kaiser Family Foundation.</li>
              <li><a href="http://healthpolicy.ucsf.edu/sites/healthpolicy.ucsf.edu/files/documents/639265-0-000-04-020 Mt Sinai Health Brief.pdf">A Shifting Health Landscape for Adolescents and Young Adults: Planning for the Implementation of Federal Health Care Reform in New York</a> (2012) examines the extent to which planning efforts in New York State are considering and responding to the critical health needs of adolescents and young adults as the state actively pursues implementation of the ACA. (Report. ICF International, the University of California San Francisco, and Mount Sinai Adolescent Health Center).</li>
            </ul>
            <p><a href="mailto:mchnavigator@ncemch.org"><strong>Please share</strong></a> trainings or examples related to the ACA in your state. We will review and add them to this section so that your work can serve as a promising practice.</p>
            <hr />
            <h2><a name="summaries" id="summaries"></a>Quick Reference Summaries to Facilitate Training</h2>
            <ul>
              <li><a href="http://www.aap.org/en-us/advocacy-and-policy/federal-advocacy/Documents/ACAImplementationFactSheets.pdf">AAP Health Reform Implementation fact sheets and resources</a> (2013) consists of a packet of one-page fact sheets on ACA implementation specifically focused on MCH. (American Academy of Pediatrics (AAP)).</li>
              <li><a href="http://www.hhs.gov/healthcare/rights/index.html">About the Law</a> and <a href="http://www.hhs.gov/healthcare/rights/law/index.html">Read the Law</a> (2013) present section-by-section outlines of the law and links to the legislation. (Health Insurance Marketplace, HealthCare, U.S. Department of Health and Human Services).
              </li>
              <li><a href="http://www.amchp.org/Policy-Advocacy/health-reform/resources/Documents/OutreachandEnrollmentFinal.pdf">The Affordable Care Act: Outreach and Enrollment</a> (2013) includes suggested steps for MCH Leaders to support outreach and ACA enrollment. (AMCHP).</li>
              <li><a href="http://www.epi.umn.edu/mch/factsheets">Factsheets About the Affordable Care Act and MCH Populations</a> (2012-2013)  provide ACA provisions and implications for specific populations. (Center for Leadership Education in Maternal and Child Public Health at the University of Minnesota).</li>
              <li><a href="http://www.hhs.gov/healthcare/facts/bystate/statebystate.html">State by State Interactive Map</a> (continually updated) describes state efforts related to the ACA.  (U.S. Department of Health and Human Services).<br />
              </li>
              <li><a href="http://kaiserfamilyfoundation.files.wordpress.com/2011/04/8061-021.pdf">Summary of the Affordable Care Act</a> (2013) provides a summary of the law and changes made to the law by subsequent legislation. It focuses on provisions to expand coverage, control health care costs, and improve health care delivery system. (Henry J. Family Kaiser Foundation).</li>
            </ul>
            <hr />
            <h2><a name="tools" id="tools"></a>Tools to Augment Training</h2>
            <ul>
              <li><a href="http://www.commonwealthfund.org/Maps-and-Data/State-Exchange-Map.aspx">State Action to Establish Health Insurance Marketplaces</a> presents an interactive map that can be used to review the status of state action on state health insurance&nbsp;marketplaces or exchanges,&nbsp;and&nbsp;view key aspects&nbsp;of state-run marketplaces. (Commonwealth Fund).</li>
              <li><a href="http://laborcenter.berkeley.edu/pdf/2012/health_reform_summary12.pdf">Summary of Affordable Care Act Provisions Affecting Children, Non-Elderly Adults and Employers</a> (2012) provides information about Medicaid/CHIP eligibility, exchanges, premium subsidies, cost sharing, health plan standards, and taxes and credits. (University of California, Berkeley Labor Center).</li>
              <li><a href="http://kff.org/interactive/zooming-in-health-reform-medicaid-uninsured-local-level">Zooming in on Health Reform:  Understanding the Potential Impact of the ACA on Medicaid and the Uninsured at the Local Level</a> (2013) present interactive maps that allow users to zoom in on their state and see how the number and composition of individuals enrolled in Medicaid or without insurance coverage could change if the state expands Medicaid. (Kaiser Commission on Medicaid and the Uninsured).</li>
            </ul>
            <hr />
            <h2><a name="additional" id="additional"></a>Additional ACA Resources</h2>
            <ul>
              <li><img src="../images/MCHDevCtr-Trans-Stat.gif" alt="MCH Workforce Development Center" width="313" height="140" border="0" class="right border" /><a href="http://www.amchp.org/Transformation-Station/Pages/Home.aspx">The National MCH Workforce Development Center</a> at UNC Chapel Hill, in cooperation with the Maternal and Child Health Bureau (MCHB), and in partnership with the Association of Maternal and Child Health Programs (AMCHP) and national experts in MCH innovation and quality improvement,  offers state and territorial Title V leaders training, collaborative learning, coaching and consultation in implementing health reform using a variety of learning platforms. The Transformation Station, hosted within the AMCHP website, contains information and resources related to the Center's four cores: access to care, quality improvement, systems integration, and change management.
                <ul>
                  <li><a href="http://www.amchp.org/Transformation-Station/Pages/ACA-101.aspx">The Affordable Care Act: A Working Guide for MCH Professionals</a> provides  an overview of major provisions in the ACA with a focus on implications for MCH populations. </li>
                  <li><a href="http://ghpc.gsu.edu/files/2015/02/MCHPlanningToolWorkbook_web.pdf">Leading through Health System Change: A Public Health Opportunity</a> helps to develop the competencies required of contemporary public health leaders to implement the Affordable Care Act (ACA) and other health system transformations. <a href="http://www.acaplanningtool.com/home">Online version of the tool</a>.</li>
                </ul>
              </li>
              <li><a href="https://www.mchlibrary.org/professionals/aca.php">Patient Protection and Affordable Care Act: Resources for Professionals</a> and <a href="https://www.mchlibrary.org/families/frb-ACA.php">Resources for Families</a> (2013) present  resources about the ACA's major provisions, policy developments, and implementation efforts. (Florida MCH Training projects and the National Center for Education in Maternal and Child Health).</li>
            </ul>
<hr />
		<p><strong>Patient Protection and Affordable Care Act (ACA): Navigating Your Way through Health Reform and the ACA</strong><br />
		January 2014; Updated April 2015, August 2015, October 2015<br />
		<strong>Authors:</strong> Beth DeFrancis-Sun, M.L.S., John Richards, M.A., AITP, MCH Navigator<br />
		<strong>Reviewers:</strong>  Jolene Bertness, MEd, NCEMCH; Anne Crotty, MPH, Child Health Specialty Clinics, Iowa; Vickie Ives, MA,  Bureau of Child, Family, and Community Wellness, Division of Public and Behavioral Health, Nevada Division Department of Health and Human Services; Lise Jankowski, Illinois Department of Public Health; Susan Brune Lorenzo, MLS, NCEMCH; Rochelle Mayer, EdD, MCH Navigator; Kathleen T Paulo, Family Health Services,   Alameda County Public Health Department; Olivia Pickett, MLS, MA, NCEMCH</p>
         </div>
</div>

<?php include('../incl/footer.html'); ?>