<?php
$section = 'academics';
$page = 'academics';
$page_title = "Advancing Academics";
include( '../../incl/header.html' );
?>
<script src="https://cdn.ncemch.org/js/jquery/jquery.min.js"></script>
<script src="https://www.mchnavigator.org/transformation/ebdm/jquery.rwdImageMaps.min.js"></script>
<script>
$(document).ready(function(e) {
	$('img[usemap]').rwdImageMaps();
});
</script>

<title>https://scholars.uab.edu/display/mslay</title>

<div class="container" style="margin-top: 2rem; margin-bottom: 2rem;">
	<?php include('../../incl/leftnav.html'); ?>
	<div class="nine columns">
		<?php include('../../incl/title.html'); ?>
		<h2>MCH Public Health Academic Journey: From PhD to Legacy </h2>
		<p><img src="../../images/mch-legacy-logo-bubbles.png" width="500" height="300" alt="Decorative image of story telling" class="right border" />The MCH Public Health Academic Journey project is a collaboration between the HRSA/MCHB-funded <a href="https://mchb.hrsa.gov/training/projects.asp?program=17">Centers of Excellence in Maternal and Child Health (CoE-MCH)</a>, the <a href="https://mchb.hrsa.gov/training/projects.asp?program=31">MCH Catalyst Program</a>, and the <a href="https://www.mchnavigator.org/">MCH Navigator</a> with support from the <a href="http://www.atmch.org/">Association of Teachers in Maternal and Child Health (ATMCH)</a>. Through recorded oral interviews, this project documents the unique paths and trajectories of MCH faculty and leaders in MCH public health academe and their relationship with the larger public health Maternal and Child Health enterprise including Title V. In the first iteration (2019-2022) the project focuses on the stories of senior MCH public health academic leaders. Beginning in 2022, the perspectives of faculty along the entire MCH public health academic career trajectory are included. For most interviewees, the MCH Academic Journey site captures information about specific events and decision points along the MCH academic timeline. However, for senior and retired academic leaders, <a href="full-interviews.php">full interviews</a> are included to specifically provide an opportunity to engage with the wisdom that senior leaders can provide to young academics interested in the field of Maternal and Child Health.</p>
		<button class="accordion"> <i class="icon mch-comments" aria-hidden="true"></i> <strong>Would you like to contribute?</strong> Contact us.</button>
		<div class="panel">
			<p>We invite you to join in sharing your journey. Please fill out the following form if you are interested in sharing either your full story or specific aspects of your MCH academic journey. If your browser doesn't allow you to fill out the form, you can always email us at <a href="mailto:mchnavigator@ncemch.org">mchnavigator@ncemch.org</a>, and someone will be in touch with you to discuss the opportunity.</p>
			<script src="https://www.emailmeform.com/builder/forms/jsform/7owWLarsdQ8a" type="text/javascript"></script>
		</div>
		<p><strong>Experiences across the MCH public health academic trajectory can be explored by clicking on the timeline or by selecting one or more of the various topics in the &quot;Alternate Access to Interviews&quot; drop-down section below.</strong></p>
		<p><img src="../../images/Legacy-2-Roadmap.png" style="height: auto; width: 100%;" usemap="#rwdImageMaps" />
			<map name="rwdImageMaps">
				<area shape="circle" coords="145,125,121" href="career.php">
				<area shape="circle" coords="280,332,118" href="service.php">
				<area shape="circle" coords="422,129,125" href="challenges.php">
				<area shape="circle" coords="570,325,117" href="credit.php">
				<area shape="circle" coords="856,343,127" href="mentoring.php">
				<area shape="circle" coords="1141,342,127" href="uniquness.php">
				<area shape="circle" coords="713,128,124" href="tips.php">
				<area shape="circle" coords="992,128,124" href="strengthen-mch.php">
			</map>
		</p>


		<button class="accordion"><i class="icon mch-book-open" aria-hidden="true"></i> Read More About the Project</button>
		<div class="panel">
			<p>The MCH Public Health Academic Journey Project, through sharing the stories of those who have walked or are currently walking in those shoes, is committed to lifting up and highlighting the various ways one can become an MCH academic. Our hope is that preserving the stories and sharing the wisdom of senior MCH academic leaders will inspire the development and success of multiple generations of faculty leaders in MCH public health academe.<u></u><u></u></p>
			<p>MCH academe comprises many fields and disciplines and as such, there are many ways to join this vibrant community.  While this manifestation of <strong>The MCH Public Health Academic Journey: From PhD to Legacy </strong>focuses on MCH academics in Schools of Public Health, particularly those who have been part of funded MCH training programs, other potential modules may evolve that involve others in MCH academe more broadly defined.</p>
			<p>This project is led by Dr. Arden Handler (UIC-SPH MCH-CoE) and Holly Grason, MA (JHU MCH-CoE) with assistance from students from various MCH programs.  John Richards and his team from the MCH Navigator help to gather, edit, and classify the collected stories and related resources in the MCH Navigator, preserving this knowledge for posterity and allowing it to be shared with future MCH academics as well as those considering this career path.</p>
			<p>Interviews from 2019 were conducted by Bethany Dominik, MPH, and Cindy San Miguel, MPH, from the University of Chicago School of Public Health Center of Excellence.&nbsp; </p>
			<p>Interviews from 2020-2021 were conducted by Kaitlin Bagley, MPH, Public Health Analyst, Division of MCH Workforce Development, HRSA&rsquo;s Maternal and Child Health Bureau.</p>
			<p>Interviews from 2021-2022 were conducted by Joyce Imafidon and Deborah Ireoluwa Makanjuola from the University of Alabama at Birmingham School of Public Health.</p>
			<p>We wish to acknowledge and extend our gratitude to Meredith Morrissette, MPH, and Michelle Menser Tissue, MPH, at HRSA's Maternal and Child Health Bureau for providing resources, advice, and encouragement through the entire process.</p>
			<div>
				<div> </div>
			</div>
			<div>
				<div> </div>
			</div>
			<div>
				<div> </div>
			</div>
		</div>


		<button class="accordion"><i class="icon mch-graduation-cap" aria-hidden="true"></i> Meet the Academic Contributors</button>
		<div class="panel"> We want to thank the many MCH academic professionals who spent the time to meet with us and discuss their insights into their careers:<br />
			<br />
			<button class="accordion">Gigliola Baruffi</button>
			<div class="panel">
				<p><img src="../../images/Gigliola-Baruffi.png" alt="Gigliola Baruffi" class="right ppic" /></p>
				<p>Gigliola Baruffi, MD, MPH, is Professor Emerita at the University of Hawaii John A. Burns School of Medicine, Department of Public Health Sciences. She directed the MCH Training Program there from1984 until 2007.  She obtained her medical degree at the University of Milan, Italy, her MPH, Pediatric and Preventive Medicine Residencies at the Johns Hopkins University. After the School of Public Health became a Department of Public Health Sciences in the School of Medicine, Dr. Baruffi developed the MCH Leadership Certificate, fully accredited by the University and much appreciated by Hawaii and Pacific Islands students. </p>
				<p> After several years of international work with the United Nations in India and Bangladesh, she joined academe first in the Department of MCH, the Johns Hopkins School of Hygiene and Public Health and then in Hawaii. As director of the MCH Training Grant she supported students and encouraged fellows. Her teaching stressed the importance of data in the management of MCH programs and her research interest focused on differences in pregnancy outcomes and young children growth between ethnic groups in Hawaii. She oversaw a program of yearly Continuing Education activities for MCH professionals of the Pacific Islands Nations. Since her retirement in 2007, Dr. Baruffi continues to participate in the review of the Title V program applications of the Pacific Islands; and remains an active member of the <em>MCH Journal</em> editorial group. </p>
				<p>Earlier in her career, in recognition of her international work in India and Bangladesh and in academe Dr. Baruffi was awarded the title of Cavaliere d&rsquo;Italia and the honorary citizenship of the city of Caravaggio (her residence in Italy). In 2021, she was awarded the Maternal and Child Health Lifetime Achievement Award by the U.S. Health Resources and Services Administration for her impact in the field.</p>
			</div>
			<button class="accordion">Zobeida Bonilla</button>
			<div class="panel"> <img src="../../images/Zobeida-Bonilla.jpg" alt="Zobeida Bonilla" class="right ppic" />
				<p><a href="https://directory.sph.umn.edu/bio/sph-a-z/zobeida-bonilla" target="_blank">Zobeida Bonilla,</a> PhD, MPH, MA, is an Associate Professor in the Division of Epidemiology and Community Health at the University of Minnesota (UMN) School of Public Health where she is Chair of the UMN <a href="https://mch.umn.edu/">Center for Excellence in MCH</a> (2020-present) as well as Director of the&nbsp;Global Health Certificate Program.  Dr. Bonilla also serves as affiliate faculty in both the Chicano and Latino Studies Department and the Gender, Women and Sexuality Studies Program in the College of Liberal Arts. Her work in&nbsp;maternal and child health focuses specifically on issues related to global health, pregnancy health education among Latinos, program evaluation, and health disparities. Globally, her work is primarily in the Caribbean region.  She has special expertise in medical anthropology and in qualitative research and program evaluation methodologies.</p>
				<p> Dr. Bonilla has&nbsp;held several program management positions including with the Latina Health Initiative of the Boston Women&rsquo;s Health Book Collective, with Eduquemos a Nuestras Mujeres of Wake County Human Services in Raleigh, North Carolina, and with the Massachusetts Department of Public Health and the West Virginia Prevention Resource Center. She continues her involvement in MCH practice while holding her graduate public health faculty position.  Most recently, <strong>Dr. Bonilla partnered with Dr. Jamie Stang</strong> to develop the Bright Spots Qualitative Research Methods Mini-Lab, designed to enhance qualitative research skills among students and community partners, particularly those in state agencies. This project fosters research and evaluation collaborations to find solutions to MCH public health needs by identifying and employing culturally-responsive, asset-based strategies rooted in the perspectives and experiences of individuals, families, and communities. </p>
				<p>Dr. Bonilla teaches several MCH courses; she is best known among students for teaching Foundations of MCH Leadership, the main MCH course for MCH graduate students. </p>
			</div>

			<button class="accordion">Christine Bozlak</button>
			<div class="panel"> <img src="../../images/Christine-Bozlak.jpg" alt="Christine Bozlak" class="right ppic" />
				<p><a href="https://www.albany.edu/sph/faculty/christine-t-bozlak" target="_blank">Christine Bozlak</a>, PhD, MPH, is an associate professor in the Department of Health Policy, Management, and Behavior at the <a href="https://www.albany.edu/sph" target="_blank">University at Albany School of Public Health</a>. She also co-directs the HRSA-funded Maternal and Child Health Program at the School of Public Health. She will serve as the co-faculty director of the Maternal and Child Health certificate program at the University at Albany, once approved. Dr. Bozlak previously co-chaired the American Public Health Association MCH Section&rsquo;s Adolescent and Young Adult Health Committee, and she is a member of the New York State Youth Development Team. She is also a member of the National MCH Workforce Development Center&rsquo;s Pipeline Team.</p>
				<p> Prior to joining the University at Albany in 2012, Dr. Bozlak was the Advocacy Program Manager for the Consortium to Lower Obesity in Chicago Children (CLOCC), a program of the Ann &amp; Robert H. Lurie Children&rsquo;s Hospital of Chicago.  She holds her MPH in health policy and management, and she completed a fellowship in the Illinois Governor&rsquo;s Office. She received her PhD in 2010 from the University of Illinois at Chicago (UIC) School of Public Health Community Health Sciences Division. She also served as an instructor and program administrative coordinator for the UIC Center of Excellence in Maternal and Child Health (formerly the Maternal and Child Health Program).</p>
				<p>Dr. Bozlak&rsquo;s research is in the area of maternal and child health, and specifically childhood obesity prevention with a focus on policy, systems, and environmental change strategies. She has conducted community-engaged research with faith-based organizations, youth-serving organizations, and organizations dedicated to addressing food insecurity. Her partnership with the Alliance of New York State YMCAs began in 2013 and has resulted in three studies focused on childhood obesity prevention. She is also a co-investigator on the Foundation for Food and Agriculture Research-funded &ldquo;Environmental and Nutritional Benefits of Food Recovery and Redistribution: A Pilot Assessment in New York&rsquo;s Capital Region&rdquo; study. Along with colleagues, she co-edited the book, &quot;<a href="https://global.oup.com/academic/product/participatory-action-research-9780190204389?cc=us&lang=en&" target="_blank">Participatory Action Research</a>&quot; (Oxford University Press).</p>
			</div>

			<button class="accordion">Dorothy C. Browne</button>
			<div class="panel"> <img src="../../images/dorothy-c-browne-headshot.png" alt="Dorothy C. Browne" class="right ppic" />
				<p><a href="https://www.linkedin.com/in/dorothy-c-browne-8b60638/" target="_blank">Dorothy C. Browne</a>, MSW, MPH, DrPH is Senior Research Scientist at Shaw University in North Carolina (2020-present). Having received her doctoral degree in Maternal and Child Health (Harvard University) and continuing as a member of the faculty in the MCH Department at the University of North Carolina, Chapel Hill (UNC), Dr. Browne has been engaged with the MCH community for over three decades. Her early research at UNC (1987-2002) was in the areas of youth violence, and adolescent high-risk behaviors. Over the years, Dr. Browne&rsquo;s expertise extended to a broad range of public health (and specific MCH) concerns. She is probably best known, however, for her longstanding and extensive focus on health disparities and her work in historically black colleges and universities.</p>
				<p>Upon leaving UNC where she remains an adjunct MCH faculty member, Dr. Browne was appointed Professor of Public Health and the senior scientist for Morgan State University&rsquo;s (MD) Prevention Sciences Research Center from 2002 until 2009. There, she also co-directed the Morgan-Hopkins Center for Health Disparities Solution, a collaborative initiative with the Johns Hopkins School of Public Health. Following her work in Maryland, Dr. Browne returned to North Carolina to serve as Dean and Professor in the School of Social Work at Norfolk State University. Among Dr. Browne&rsquo;s subsequent public health academic leadership accomplishments are her roles in the Office of the Provost at North Carolina A&amp;T State University, as Founding Dean and Professor at Jackson State University—where she initiated the establishment of the School of Public Health in 2016—and her role as Provost/Vice President for Academic Affairs at Bennett College. </p>
				<p>Alongside these academic roles, Dr. Browne maintains a presence in public health practice, where she is deeply engaged in community public health activities. Her consultation for community-based researchers on interventions designed to reduce health disparities represents one of the many ways she combines public health academics and public health practice. </p>
				Dr. Browne&rsquo;s work related to maternal and child health is extensively published, including her work on risk and resilience in vulnerable African-American adolescents as well her focus on factors leading to disparities in health outcomes and ways in which community structures such as social capital enable individuals and families to succeed in adverse situations. Dr. Browne is lead author of a chapter on Rights, Justice, and Equity in the Fourth Edition of the well-known textbook,<em> Maternal and Child Health: Programs, Problems, and Policy in Public Health</em> (Kirby and Verbiest, 2022).
			</div>

			<button class="accordion">Noel Chavez</button>
			<div class="panel">
				<p><img src="../../images/Noel-Chavez.jpg" alt="Noel Chavez" class="right ppic" /></p>
				<p><a href="https://publichealth.uic.edu/profiles/chavez-noel/">Noel Chávez</a>, PhD, RD, LDN,&nbsp;is an Associate Professor Emerita in the Community Health Sciences Division of the University of Illinois School of Public Health. She served as faculty for the <a href="https://maternalchild.uic.edu/">MCH Center of Excellence at UIC</a> for many years, including during her tenure as Director from 2003-2005. Her research centers on the health and nutrition status of Latinos and other underrepresented groups, particularly that of children and families. Dr. Chávez&rsquo;s major studies addressed Latino child health, including studying maternal environmental and dietary influences on subsequent development of asthma in children, dietary acculturation, family health and nutrition attitudes, and behaviors in Latinx families with young children. </p>
				<p> Dr. Chávez has served as a proposal reviewer for the USDA NIFA Childhood Obesity Research panel, and is a member of the editorial boards for the&nbsp;<em>Journal of Nutrition Education and Behavior</em>&nbsp;and the&nbsp;<em>Maternal and Child Health Journal</em>. She served on an IOM Panel to Examine the adequacy of food resources and SNAP allotments. She is an active member of both the Food and Nutrition Section where she served as Section Chair, and the Latino Caucus of the American Public Health Association.</p>
				<p><a href="noel-chavez.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Martha Coulter</button>
			<div class="panel">
				<p><img src="../../images/martha-coulter.jpg" alt="Martha Coulter" class="right ppic" /></p>
				<p>Martha Coulter, DrPH, MSW, is Professor Emerita in the Department of Community and Family Health at the University of South Florida College of Public Health (2018-present). She directed the MCH Center of Excellence there from 2010-2018. Maternal and child health has been at the forefront of her public health passion for decades, focusing her research on family violence. </p>
				<p> Dr. Coulter had a distinguished practice career before moving into academe. She served as the state program director of the Developmental Evaluation Centers Program at the North Carolina Division of Health Services and as a lecturer at the UNC School of Public Health. In 1986 she moved to Florida to become the health officer for Prevention and Early Intervention at the Florida Department of Health in Children&rsquo;s Medical Services (Title V, SSA) where she was tasked with implementing the newly passed Public Law 99-457 which provides early intervention services to infants and young children.</p>
				<p>In 1994 Dr. Coulter was named Director of the USF COPH&rsquo;s Harrell Center for the Study of Family Violence, a center focused on integrating knowledge with best practices to strengthen community responses to family violence. The center conducts and translates research into usable information for practitioners to provide education and training, as well as serves as an advocacy center.</p>
				<p><a href="martha-coulter.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Julie Deardorff</button>
			<div class="panel">
				<p><img src="../../images/Julie-Deardorff.jpg" alt="Julie Deardorff" class="right ppic" /></p>
				<p><a href="https://publichealth.berkeley.edu/people/julianna-deardorff/">Julianna Deardorff</a>, PhD, is an Associate Professor (2014-present) in the Division of Community Health Sciences and head of the Maternal, Child and Adolescent Health program, in the School of Public Health at UC Berkeley, where she teaches graduate level courses in Adolescent Health and Evaluation of Health and Social Programs. She is the Director of UC Berkeley&rsquo;s MCHB-funded <a href="https://mcah.berkeley.edu/center-excellence">MCH Center of Excellence</a> (2015-present). </p>
				<p> Dr. Deardorff holds masters and doctorate degrees in clinical psychology, with an emphasis on adolescence, and completed her clinical internship at Lucile Packard Children&rsquo;s Hospital at Stanford University. Before joining the School of Public Health, she was Assistant Professor in Epidemiology and Biostatistics at UCSF. Dr. Deardorff&rsquo;s research focuses on pubertal development, sexual and reproductive health during adolescence and young adulthood, mental health, and related risk and protective factors, particularly among young Latinos in the US. She also has expertise in social and contextual factors related to early adversity, pubertal timing and health outcomes.</p>
			</div>
			<button class="accordion">Eugene DeClercq</button>
			<div class="panel">
				<p><img src="../../images/Eugene-Declercq.jpg" alt="Eugene Declercq" class="right ppic" /></p>
				<p><a href="https://www.bu.edu/mchcenterofexcellence/profile/gene-declercq/">Eugene DeClercq</a>, PhD., is a Professor in Community Health Sciences at Boston University School of Public Health, <a href="https://www.bu.edu/mchcenterofexcellence/">Center of Excellence in Maternal and Child Health</a>.  He is currently (2021) the BUSPH Assistant Dean for DrPH Education. Dr. DeClercq&rsquo;s academic work combines formal training in political science with almost twenty years of experience as a certified childbirth educator to examine policy and practice related to childbirth in the US and abroad. His recent work in examining maternal mortality and morbidity in the US has emphasized the importance of systems approaches to improving women&rsquo;s health. This requires a focus on women&rsquo;s health in the community as well as in clinical settings and not only during pregnancy, but throughout the life course. </p>
				<p>Dr. DeClercq was principal investigator on two NIH funded collaborative projects examining child and maternal outcomes associated with Assisted Reproductive Technologies (MOSART project) and is one of the founders of the Massachusetts Pregnancy to Early Life Longitudinal (PELL) data system. He also is active in a variety of public health projects in his hometown of Lawrence, Massachusetts.</p>
				<p> Dr. DeClercq is a past president of the Association of Teachers of Maternal and Child Health and has been a recipient of the Norman Scotch Award for outstanding teaching at BUSPH. He is also a recipient of the Martha May Eliot Award from the American Public Health Association for service to maternal and child health and the Greg Alexander Award for Research in Maternal and Child Health Epidemiology.</p>
				<p><a href="eugene-declercq.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Trish Elliot</button>
			<div class="panel">
				<p><img src="../../images/trish-elliott.jpg" alt="Trish Elliot" class="right ppic" /></p>
				<p><a href="https://www.bu.edu/mchcenterofexcellence/profile/271/">Trish Elliott</a>, DrPH, at Boston University School of Public Health, <a href="https://www.bu.edu/mchcenterofexcellence/">Center of Excellence in Maternal and Child Health</a>, is a Clinical Associate Professor of Community Health Sciences dedicated to training future practitioners of public health. She teaches courses in maternal child and adolescent health, leadership, and program management. Dr. Elliott uses a combination of simulation, case method, and practice-based learning in the classroom and is committed to using innovative approaches in academic-practice collaboration. Dr. Elliott directs the Practice Fellowship Program of the Maternal and Child Health Center of Excellence, connecting exceptional master's degree students with year-long placements in public health organizations, and leads a multi-state initiative to facilitate co-learning for public sector MCH workforce development.&nbsp;&nbsp;She serves as the Director of the Doctor of Public Health program, a school-wide doctoral degree in leadership, management, and policy, preparing students for high-level positions in public health practice, and&nbsp;as the Director of Education for the Department of Community Health Sciences.&nbsp; </p>
				<p>Dr. Elliott&rsquo;s academic and practice interests focus on using implementation science, systems science, and process evaluation methods to improve the health of vulnerable populations. She is particularly interested in adolescent and family access to health services, the intersection of mental health and juvenile justice, school health, academic-practice partnerships, and health policies at the local, state, and federal level. Dr. Elliott joined the department of Community Health Sciences as faculty in 2013, after teaching for four years in an adjunct capacity. Prior to her work in academe, she spent ten years in management within the health sector overseeing complex projects.  She received a BA in Psychology from Colby College, a MPH degree with dual concentrations in Social and Behavioral Sciences, and Maternal and Child Health from Boston University where she also completed her DrPH in Maternal and Child Health. </p>
			</div>
			<button class="accordion">Sylvia Guendelman</button>
			<div class="panel">
				<p><img src="../../images/Sylvia-Guendelman.jpg" alt="Sylvia Guendelman" class="right ppic" /></p>
				<p><a href="https://publichealth.berkeley.edu/people/sylvia-guendelman/">Sylvia Guendelman</a>, PhD, MSW, is Professor Emeritus of Community Health and Health Development and Maternal &amp; Child Health at the<a href="https://publichealth.berkeley.edu"> UC Berkeley School of Public Health</a>. She served as Academic Chair of the MCH program between 2000 and 2017 and is the Founder and Advisory Committee Chair of the Wallace Center for Maternal, Child and Adolescent Health aimed at advancing health through technology. Previously, Dr. Guendelman served as Chair in the World Health Organization&rsquo;s Regional Panel on Reproductive Health for the Americas. Prior, she worked as a clinical social worker at Children's Hospital in Oakland, CA. </p>
				<p>Dr. Guendelman&rsquo;s broad research interests include women&rsquo;s health, health along the U.S. Mexico border, reproductive health of immigrant women, and access to health care for disadvantaged populations including the working poor. Recently, she was awarded best project in applied nutrition in a study assessing weight status of women in Mexico and with US-born Mexican American women and received the Liberty Mutual award for best paper in Ergonomics. </p>
				<p>Her expertise areas also include health policy and management, health and social behavior, public health, and multicultural health. She has published a variety of work on immigrant health, health disparities and the health of working women. Some of her current research focuses on assessing pregnant women and mother&rsquo;s engagement with digital health technologies and analyzing Google search queries to understand population health concerns. </p>
			</div>
			<button class="accordion">Bernard Guyer</button>
			<div class="panel">
				<p><img src="../../images/Bernard-Guyer.jpg" alt="Bernard Guyer" class="right ppic" /></p>
				<p><a href="https://publichealth.jhu.edu/faculty/288/bernard-guyer">Bernard Guyer</a>, MD, MPH, is Professor Emeritus at the Johns Hopkins Bloomberg School of Public Health, Department of Population, Family and Reproductive Health (PFRH) (2010-present).  Dr. Guyer directed the <a href="https://publichealth.jhu.edu/center-of-excellence-in-maternal-and-child-health">MCH Center of Excellence</a> from 1989 to 2010 and chaired the Department of PFRH during the same time period. Throughout his public health career he conducted research focused on improving the health of children, their mothers, and their families -- in this country and in the developing world. The specific areas of his research included, immunization against vaccine-preventable diseases, childhood injury and injury prevention, the causes and strategies to reduce infant mortality, and interventions to strengthen human development during the early portion of the lifespan. </p>
				<p> A physician trained in both preventive medicine and pediatrics, Dr. Guyer served for seven years (1979-1986) as director of the state MCH (Title V) program in Massachusetts, and for five years before that as a CDC medical epidemiologist with national and international service. He directed the MPH Program at the Harvard School of Public Health in the three years before his tenure at Hopkins. He chaired or was a member of both state and national committees on childhood injury prevention, outreach for prenatal care, infant mortality, and Medicaid, including as a member of the Institute of Medicine.</p>
				<p>Dr. Guyer and colleagues have further contributed to providing research that can be used to strengthen the way in which the MCH field addresses its most pressing problems across the lifespan.  He has been awarded the highest honors by many national professional organization, including the APHA  Martha May Eliot Award in 2003.</p>
				<p><a href="bernard-guyer.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Arden Handler</button>
			<div class="panel">
				<p><img src="../../images/ardenhandler.jpg" alt="Arden Handler" class="right ppic" /></p>
				<p><a href="https://publichealth.uic.edu/profiles/arden-handler/">Arden Handler</a>, DrPH, is the Director of the <a href="https://maternalchild.uic.edu/">Center of Excellence in Maternal and Child Health</a> (2005-present) and a Professor in the Community Health Sciences division of the of Illinois at Chicago School of Public Health. Dr. Handler&rsquo;s research career reflects her long-standing commitment to reducing disparities and improving the health of women, pregnant and postpartum persons, children, and families. Her specific interest is the exploration of factors that increase the risk for disparities in adverse pregnancy outcomes and examining ways in which the health care delivery system, particularly how prenatal care, postpartum care, and preconception/interconception/well-woman care can ameliorate these risks and reduce disparities and inequities. Other research and teaching interests include maternal and child health advocacy and policy, building the analytic capacity of the MCH workforce (MCH epidemiology), and the structure and functioning of the public health delivery system. </p>
				<p>Dr. Handler is PI of the evaluation of the Illinois Breast and Cervical Cancer Program, PI of the evaluation of Family Connects Chicago, co-PI for the evaluation of OCEAN Healthy Start, and is working on a number of projects focused on the delivery of health care in the postpartum period. Dr. Handler is Co-PI (multiple PIs) of the HRSA funded <em>Innovations to ImPROve Maternal OuTcomEs in Illinois</em> (I PROMOTE-IL). She is a former member of the Secretary&rsquo;s Advisory Committee on Infant Mortality (SACIM) and a nationally renowned leader in maternal and child health advocacy, policy, epidemiology, and public health system improvement.</p>
				<p>Dr. Handler is the recipient of many state and national awards, most notably the Association of Teachers of Maternal and Child Health Loretta Lacey Award for Academic Leadership in 1996, MCHB&rsquo;s Vince Hutchins Partnership Award in 2016, and was a 2021 HRSA Lifetime Achievement Award recipient.  She served as President of the Association of Teachers of Maternal and Child Health 2000-2002.</p>
				<p><a href="arden-handler.php">Access the full interview here</a>.<br>
				</p>
			</div>
			<button class="accordion">Carol Hogue</button>
			<div class="panel">
				<p><img src="../../images/Carol-Hogue.jpg" alt="Carol Hogue" class="right ppic" /></p>
				<p><a href="https://www.sph.emory.edu/faculty/profile/index.php?FID=carol-hogue-102">Carol Hogue</a>,&nbsp;PhD, MPH, is Professor Emerita at Emory University Rollins School of Public Health. In 1992 Dr. Hogue was appointed to the Jules and Uldeen Terry Chair of Maternal and Child Health and established the Women&rsquo;s and Children&rsquo;s Center, where she Directed Emory&rsquo;s <a href="https://mch.emory.edu/">MCH Center of Excellence</a> (2015-2019).  Dr. Hogue began her career as a social worker in Knoxville, Tennessee, and later moved to North Carolina in 1969 where she became widely known for using surveillance systems, developing psychosocial measurement of racial disparities, and conducting groundbreaking epidemiologic studies of perinatal outcomes. </p>
				<p> A former Director of the federal Centers for Disease Control, Division of Reproductive Health (1988-92) and on faculties in Biometry at the University of Arkansas for Medical Science (1977-82) and the UNC School of Public Health Department of Biostatistics (1974-77), Dr. Hogue&nbsp;initiated many of the current CDC reproductive health programs, including the Pregnancy Risk Assessment Monitoring System (PRAMS), the National Pregnancy Mortality Surveillance System, and the National Infant Mortality Surveillance (NIMS) project&nbsp;that launched&nbsp;the national and state-level development and use of linked birth and death records.&nbsp;</p>
				<p>Among her many honors, Dr. Hogue served as President of the Society for Epidemiologic Research (1988-89) and as the President of the American College of Epidemiology (2002-04). She was also a recipient of the MCH Coalition&rsquo;s National Effective Practice Award in 2002 and Greg Alexander Award for Advancing Knowledge (2016).</p>
				<p><a href="carol-hogue.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Charvonne Holliday</button>
			<div class="panel">
				<p><img src="../../images/charvonne-holliday.png" alt="Charvonne Holliday" class="right ppic" /></p>
				<p><a href="https://publichealth.jhu.edu/faculty/3637/charvonne-n-holliday">Charvonne N. Holliday</a>, PhD, MPH is an Assistant Professor in the Department of Population, Family and Reproductive Health at Johns Hopkins Bloomberg School of Public Health (2018-present).  She was a Postdoctoral Fellow at Hopkins 2016-2017.  Dr. Holliday is trained in behavioral and community health, with research experience and public health practice related to women&rsquo;s health and community-oriented approaches to positive change. </p>
				<p> Dr. Holliday is committed to understanding racial/ethnic disparities that persist in intimate partner violence (IPV) and women&rsquo;s sexual/reproductive health by examining social and structural determinants of health. Current research includes examining racial/ethnic differences in reproductive coercion and women&rsquo;s contraceptive decision making, mitigating barriers to help-seeking for survivors of IPV, and exploring innovative intervention strategies for male IPV perpetrators.</p>
				<p> Current research includes examining racial/ethnic differences in reproductive coercion and women&rsquo;s contraceptive decision making, mitigating barriers to help-seeking for survivors of IPV, and exploring innovative intervention strategies for male IPV perpetrators. Dr. Holliday applies a mixed-methods approach, including participatory research methods like concept mapping.</p>
			</div>
			<button class="accordion">Colleen Huebner</button>
			<div class="panel">
				<p><img src="../../images/colleen-huebner.png" alt="Colleen Huebner" class="right ppic" /></p>
				<p><a href="http://depts.washington.edu/hserv/faculty/Huebner_Colleen">Colleen Huebner</a>, PhD, MPH, is Professor Emerita at the University of Washington&rsquo;s School of Public Health. She was a faculty member of the <a href="https://sph.washington.edu/">University of Washington&rsquo;s Center of Excellence in MCH</a>, Science and Practice for 25 years as a teacher, assistant director, and Director (2002-2014). Dr. Huebner&rsquo;s research focused on the design, implementation and evaluation of community- and clinic-based preventive intervention programs for young children and families in poverty including programs to prevent infant maltreatment, promote early language development, emergent literacy and protect children&rsquo;s oral health. </p>
				<p> Trained in Developmental Psychology and Epidemiology Dr. Huebner taught courses in needs assessment, program planning and evaluation, health policy, and the historical and current influence of Title V on women, children and families in the U.S. She mentored the research of over 70 MPH students, PhD students and post-docs and helped guide many of their projects to peer-reviewed publication.</p>
				<p> She was a member of several interdisciplinary research teams at the University and worked with numerous collaborators including families and practitioners in rural communities in Washington, Oregon, Colorado, and in Alaska Native villages; people working in public libraries, community health clinics, Head Start programs, early intervention and family centers in Seattle, Chicago, and in the Republic of the Marshall Islands. </p>
				<p>Dr. Huebner, along with colleagues in MCH academe, field-based public health and clinical practice, established the groundwork for several MCH resources of national scope including the MCH Leadership Competencies and the MCH Navigator. She was on the editorial board of the <em>Maternal and Child Health Journal</em> for many years and, in 2005, received the Loretta P. Lacey Academic Leadership Award of the Association of Teachers of Maternal and Child Heath.</p>
			</div>
			<button class="accordion">Russell Kirby</button>
			<div class="panel">
				<p><img src="../../images/Russell-Kirby.jpg" alt="Russell S. Kirby" class="right ppic" /></p>
				<p><a href="https://health.usf.edu/publichealth/overviewcoph/faculty/russell-kirby">Russell S. Kirby</a>, PhD, MS, FACE, is the Distinguished University Professor, Marrell Endowed Chair, and Faculty Strategic Area Lead for Population Health Science, University of South Florida (2008-present) where he also is a faculty member of USF&rsquo;s Center of Excellence in MCH.  He is a perinatal and pediatric epidemiologist trained in the social sciences, with a PhD in human geography (Wisconsin, 1981) and MS in preventive medicine-epidemiology (Wisconsin, 1991). Dr. Kirby worked at the state health agencies in Wisconsin and Arkansas, on the faculties of the Department of Pediatrics, University of Arkansas for Medical Sciences, and Department of Obstetrics and Gynecology, Milwaukee Clinical Campus, University of Wisconsin Medical School.  He was a faculty member at the MCH Center of Excellence at the School of Public Health, University of Alabama at Birmingham prior to joining the faculty of the University of South Florida in 2008.</p>
				<p> Birth defects and developmental disabilities research, surveillance and epidemiology have been a major interest since the early 1980s.  Dr. Kirby&rsquo;s research interests, however, extend well beyond; they include the public health implications of health policies and programs, with special reference to perinatal and maternal/child health; population health informatics and perinatal/pediatric studies in genetics.</p>
				<p>Dr. Kirby has authored more than 300 peer-reviewed articles and actively participates in the editorial process as a peer reviewer or editorial board member for numerous journals. He was elected Fellow in the American College of Epidemiology in 1996 and served as its president in 2018-19. Dr. Kirby previously served as President of the National Birth Defects Prevention Network, the Wisconsin Association for Perinatal Care and the Arkansas Perinatal Association, Society for Pediatric and Perinatal Epidemiologic Research, and the Association of Teachers of Maternal and Child Health. </p>
			</div>
			<button class="accordion">Jonathan Kotch</button>
			<div class="panel">
				<p><img src="../../images/Jonathan-Kotch.jpg" alt="Jonathan Kotch" class="right ppic" /></p>
				<p><a href="https://sph.unc.edu/adv_profile/jonathan-b-kotch-md/">Jonathan Kotch</a>, MD, MPH, a board-certified medical specialist in pediatrics and preventive medicine, was on the active faculty of UNC's <a href="https://sph.unc.edu/mch/maternal-and-child-health/">Department of Maternal and Child Health</a> for 37 years. Dr. Kotch was Director of UNC&rsquo;s Center of Excellence from 2002-2005 and served as Chair of the Department of MCH for many years. Currently Emeritus Research Professor, Dr. Kotch was the Carol Remmer Angle Distinguished Professor of Children's Environmental Health until he entered phased retirement in 2013. </p>
				<p> His expertise in health and safety in out-of-home child care has resulted in national training programs for child care health consultants across the country, and he was co-chair of the steering committee that produced the third edition of Caring for Our Children: National Health and Safety Performance Standards; Guidelines for Early Care and Education Programs.</p>
				<p> As the Principal Investigator of one of five local sites of the Longitudinal Studies Consortium on Child Abuse and Neglect, Dr. Kotch was responsible for the North Carolina cohort, studied from birth until age 18. A follow-up funded by NIDA has just concluded (2019).</p>
				<p>He edited the first three editions of&nbsp;<em>Maternal and Child Health: Programs, Problems, and Policy in Public Health </em>(Jones and Bartlett) and is the recipient of the Martha May Eliot Award (APHA), the John C. MacQueen Lectureship (AMCHP), the Academic Leadership Award (ATMCH), and the Young Professional of the Year Award (MCH Section).</p>
				<p><a href="jonathan-kotch.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Milton Kotelchuck</button>
			<div class="panel">
				<p><img src="../../images/Milton-Kotelchuck.jpg" alt="Milton Kotelchuck" class="right ppic" /></p>
				<p><a href="https://researchers.mgh.harvard.edu/profile?profile_id=3823943">Milton Kotelchuck</a>, MPH, PhD, is currently (2021) Professor of Pediatrics at Harvard Medical School and Senior Scientist in Maternal and Child Health at the Center for Child &amp; Adolescent Health Research and Policy at Massachusetts General Hospital. Formerly, he was Professor and Chair of the Maternal and Child Health Departments at Boston University School of Public Health where he served as Director of the <a href="https://www.bu.edu/mchcenterofexcellence/">MCH Center of Excellence</a> from 2001-2008. He was Professor and Chair of the MCH Department at the University of North Carolina at Chapel Hill before moving to Boston. </p>
				<p> Dr. Kotelchuck has been active in advancing MCH research, practice, policy and training in the MCH field for nearly 50 years; to that end, he has served on numerous local, state, national and professional MCH advisory committees. He has advocated for the advancement of MCH epidemiology and data systems and for the reintegration of MCH life course/social determinant of health perspectives into the MCH field. His specific research interests include examination of the adequacy and content of prenatal care, racial disparities in birth outcomes, maternal morbidity, immigrant health, child nutrition, fatherhood/men&rsquo;s health, child health services, and health data policy. Dr. Kotelchuck has extensively evaluated public health programs to improve birth outcomes and child health status. He developed the widely used Adequacy of Prenatal Care Utilization (APNCU) Index, the so-called Kotelchuck Index. </p>
				<p>Dr. Kotelchuck was the founding and initial Editor of the&nbsp;<em>Maternal and Child Health Journal</em>. In Dr. Kotelchuck was awarded the first National MCH Epidemiology Award for &ldquo;Advancing Knowledge&rdquo; from the Coalition for Excellence in MCH Epidemiology in 2000.  In 2010, he was awarded the Martha May Eliot Award, the top honor given for Maternal and Child Health by the American Public Health Association.</p>
				<p><a href="milton-kotelchuck.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Michael Kramer</button>
			<div class="panel">
				<p><img src="../../images/michael-kramer.jpg" alt="Michael Kramer" class="right ppic" /></p>
				<p><a href="https://www.sph.emory.edu/faculty/profile/index.php?FID=michael-kramer-12566">Michael Kramer</a>, PhD, MMSc, is a social epidemiologist, health disparities scholar, and the Director of the <a href="https://mch.emory.edu">Emory Center of Excellence in Maternal and Child Health Education</a>, Science, and Practice. He was also a HRSA MCHB trainee himself. His research seeks to advance theory for the social determinants of health, develop and implement novel methods for measuring and quantifying the biological embodiment of social experiences and environments, and advancing impactful science focusing on improving the health of women and children. His research has been supported by NIH, HRSA, CDC, and March of Dimes. </p>
				<p>Dr. Kramer's current projects focus on building the evidence base to inform social and community policies to eliminate disparities in severe maternal morbidity and mortality. He currently serves as the co-chair of the Georgia maternal mortality review committee.</p>
			</div>
			<button class="accordion">Lew Margolis</button>
			<div class="panel">
				<p><img src="../../images/margolis_lewis_200sq.jpg" alt="Lew Margolis" class="right ppic" /></p>
				<p><a href="https://sph.unc.edu/sph-news/margolis-honored-with-amchp-leadership-award/">Lew Margolis</a>, MD, MPH, is Professor Emeritus at the University of North Carolina Gillings School of Global Public Health.  He retired in 2018 after serving on the faculty for 28 years. He held the position of Associate Professor in the Department of Maternal and Child Health, serving as Director of <a href="https://sph.unc.edu/mch/center-of-excellence/">UNC&rsquo;s MCH Center of Excellence</a> from 2015-2018. </p>
				<p> Dr. Margolis earned a reputation among MCH students as a passionate and dedicated teacher, mentor and advisor. He was especially committed to challenging students to think critically and consider the many sides of complex public policy issues. He was a co-lead of the UNC MCH Interdisciplinary Leadership Development program which brought together students and faculty from five MCHB-funded training programs.</p>
				<p> Dr. Margolis is the recipient of the Vince Hutchins Leadership Award from the Association of Maternal and Child Health Programs.</p>
				<p><a href="lew-margolis.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Lois McClosky</button>
			<div class="panel">
				<p><img src="../../images/Lois-McClosky.jpg" alt="Lois McCloskey" class="right ppic" /></p>
				<p><a href="https://www.bu.edu/mchcenterofexcellence/profile/lois-mccloskey/">Lois McCloskey</a>, DrPH, serves at Boston University School of Public Health as Associate Chair of the Department of Community Health Sciences, Co-Director of the MCH Certificate, and Director of the <a href="https://www.bu.edu/mchcenterofexcellence/">Center of Excellence in Maternal and Child Health</a><u> </u>(2008-present). She began her public health career 30 years ago as an applied anthropologist and educator of community health workers in Nepal. In both international and domestic settings, her work focuses on the disconnects between the lives of women and the health care systems meant to serve their needs across the life course. As an educator, Dr. McCloskey specializes in practice-based courses that engage students in the application of their skills and knowledge in real life organizations, addressing real life challenges.</p>
				<p> Dr. McCloskey co-founded the Institute for Urban Health Policy and Research for the Boston Department of Health and Hospitals and served as its Senior Research Scientist for 7 years before joining the faculty of Boston University. During her tenure at the Institute, she led research and community action initiatives designed to mobilize community residents, health professionals, academics, and policy-makers to eliminate racial disparities in infant death and pre-term birth. The findings led to fundamental changes in how perinatal health services are delivered to women of African descent in Boston. </p>
				<p>Dr. McCloskey co-founded the Women&rsquo;s Health Committee of the MCH Section of the American Public Health Association, is a member of the Association of Teachers of Maternal and Child Health and is a reviewer for the <em>Women&rsquo;s Health Journal</em>, the <em>Maternal and Child Health Journal</em>, the <em>Journal of the Poor and Under-served,</em> <em>Public Health Reports</em>, <em>BMC Health Services,</em> and <em>BMC Pregnancy and Birth.</em></p>

			</div>
			<button class="accordion">Marie C. McCormick</button>
			<div class="panel">
				<p><img src="../../images/Marie-McCormick.jpg" alt="Marie McCormick" class="right ppic" /></p>
				<p><a href="https://www.hsph.harvard.edu/profile/marie-clare-mccormick/">Marie C. McCormick</a>, MD, ScD, MPH&nbsp;is the Sumner &amp; Esther Feldberg Professor of Maternal &amp; Child Health Emerita in the Department of Social and Behavioral Sciences at the Harvard T. H. Chan School of Public Health, and Senior Associate for Academic Affairs in the Department of Neonatology at the Beth Israel Deaconess Medical Center (2019-present). In her role at the Harvard T. H. Chan School of Public Health, she was the director of the <a href="https://www.hsph.harvard.edu/mch-center-excellence/">Maternal and Child Health Center of Excellence</a> from 1991 to 2019. During that time she expanded the program to be school-wide, attracting a diverse group of students. </p>
				<p> Dr. McCormick is best known for leading several large national studies, including the evaluation of the National Perinatal Regionalization Program funded by the Robert Wood Johnson Foundation (RWJF) and the evaluation of the original national Healthy Start Program which documented the use of case management and of Fetal and Infant Mortality Reviews in this program. In her study of the Infant Health and Development Program (IHDP) she examined the role of early educational intervention in improving the outcomes of premature, low birth weight infants in a multi-site trial. Phase I of the project included the provision of a combination of home-visiting and center based developmental services, with longitudinal follow-up until age 18 years.</p>
				<p>Dr. McCormick has been the member of several professional organizations and the recipient of many awards and honors. Of most significance is her several roles in the Academic Pediatric Association. She was elected to membership in the Institute of Medicine, in 1997, and has served on 16 committees, chairing five. Her work chairing the Immunization Safety Review Committee earned her the David Rall Medal for exceptional service. Dr. McCormick was the invited presenter for the APHA Martha May Eliot Forum in 1988.</p>
				<p><a href="marie-mccormick.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Cynthia Minkovitz</button>
			<div class="panel">
				<p><img src="../../images/Cynthia-Minkovitz.jpg" alt="Cynthia Minkovitz" class="right ppic" /></p>
				<p><a href="https://publichealth.jhu.edu/faculty/480/cynthia-schaffer-minkovitz">Cynthia Minkovitz</a>, MD, MPP, is the William H. Gates, Sr. Professor and Chair of the Department of Population, Family and Reproductive Health at Johns Hopkins Bloomberg School of Public Health, and a Professor of Pediatrics in the School of Medicine.  Dr. Minkovitz is Director of the <a href="http://jhu-mchcenterofexcellence.org">Johns Hopkins Center of Excellence in MCH</a> (2020-present) and she has led the MCH Postdoctoral Fellowship Program since 2015. Her research focuses on enhancing the quality of preventive services and understanding the impact of systems reforms on the health and well-being of children and families. </p>
				<p> Dr. Minkovitz serves on the Leadership Team for the Home Visiting Applied Research Collaborative (HARC). HARC&rsquo;s mission is to promote the use of innovative research methods to advance precision home visiting and to accelerate the integration of results into practice. Dr. Minkovitz has led national and state evaluations including Healthy Steps for Young Children, the Dyson Community Pediatrics Training Initiative, and New Jersey Project LAUNCH. She also co-led efforts to develop a framework to promote coordination in the early childhood system and collaborates on New Jersey&rsquo;s Preschool Development Grant and Maryland&rsquo;s Prenatal to Three Initiative.</p>
				<p>Dr. Minkovitz has received numerous awards including the Academic Pediatric Association Research Award as well as institutional awards for excellence in teaching and mentoring.</p>
			</div>
			<!-- <button class="accordion">Emmanuel Ngui</button>
      <div class="panel">
        <p><img src="../../images/Emmanual-Ngui.jpg" alt="Emmanuel Ngui" class="right ppic" /></p>
        <p><a href="https://uwm.edu/publichealth/directory/ngui-emmanuel/">Emmanuel Ngui</a>, DrPH, MSc,  is an Associate Professor in the Department of Community Behavioral Health Promotion at the Joseph J. Zilber School of Public Health, University of Wisconsin Milwaukee where he directs the <a href="https://uwm.edu/publichealth/academics/maternal-child-health-certificate/#tab-wz97-faculty">MCH Graduate Catalyst Program</a> (2020-present).  He also has served as the Director of MPH Program there since 2016 and has ongoing affiliations with the school&rsquo;s Center for Urban Population Health and the Institute for Intercultural Research, School of Education. Prior to his position at the school of public health, Dr. Ngui was a member of the faculty of the Medical College of Wisconsin from 2004-2011; he continues his connection with the College as an affiliate the Institute of Health and Society.</p>
        <p> Dr. Ngui&rsquo;s broad research interests include health inequalities in maternal and child health populations and the role of social determinants of health in birth outcomes and child health and wellbeing. These broad areas of interest and expertise are reflected in the courses he teaches – Community Engagement and Participatory Research, MCH Policy and Planning, and Theories and Models of Health Behavior.</p>
        <p>His active research areas are: racial/ethnic inequalities in birth outcomes and community/policy level interventions and engagement; access, systems of care, and use of health services by children, particularly racial/ethnic minority children and those with special health care needs; and ethical issues in engaging racial/ethnic MCH populations in biomedical and emerging genetic research. Within that context, he&rsquo;s focused much of his work on the impact of African-American fathers on maternal and child health.</p>
      </div> -->
			<button class="accordion">Donna Petersen</button>
			<div class="panel">
				<p><img src="../../images/Donna-Petersen.jpg" alt="Donna Petersen" class="right ppic" /></p>
				<p><a href="https://health.usf.edu/publichealth/overviewcoph/faculty/dpeters">Donna Petersen</a>, ScD, MHS, is Professor and Dean of the College of Public Health at the <a href="https://health.usf.edu">University of South Florida</a> (2004 – present). She earned her masters and doctoral degrees in maternal and child health from the Johns Hopkins School of Hygiene and Public Health. She has held faculty and senior leadership positions at the University of Alabama at Birmingham School of Public Health (1996-2003) at the University of Minnesota School of Public Health, and served as Director of the Division of Family Health (Title V MCH) at the Minnesota Department of Health. (1990-1995). </p>
				<p> Dr. Petersen has provided extensive technical assistance and training to over 25 state health departments in the areas of needs assessment, data system development, systems level accountability and the development of population-based indicators. She has served on numerous boards, commissions and task forces and is Editor Emerita of the&nbsp;<em>Maternal and Child Health Journal</em>, founding member and past president of the National Board of Public Health Examiners, past Chair of the Council on Education for Public Health, and immediate-past Chair of the Association of Schools and Programs of Public Health.&nbsp;</p>
				<p>Dr. Petersen has been honored for her work by the American Public Health Association, the Association of Teachers of Maternal and Child Health, the National Healthy Mothers, Healthy Babies Coalition, the Delta Omega National Public Health Honor Society, the National Coalition for Excellence in MCH Epidemiology, the federal Bureau of Maternal and Child Health and the Association of Maternal and Child Health Programs.</p>
				<p><a href="donna-petersen.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Cheri Pies</button>
			<div class="panel">
				<p><img src="../../images/Cheri-Pies.jpg" alt="Cheri Pies" class="right ppic" /></p>
				<p><a href="https://publichealth.berkeley.edu/people/cheri-pies/">Cheri Pies</a>&nbsp;DrPH, MSW, is clinical Professor Emeritus at the<a href="https://publichealth.berkeley.edu"> UC Berkeley School of Public Health</a> (2019-Present).  She was Director of Berkeley&rsquo;s <a href="https://mcah.berkeley.edu/center-excellence">MCH Center of Excellence</a> from 2011 to 2017.   Dr. Pies is best known for her role as the Principal Investigator for the Best Babies Zone Initiative (2012 to 2019), a place-based multi-sector approach to reducing infant mortality through community driven transformation. Prior to entering academe, Dr. Pies was the Director of Family, Maternal and Child Health programs at Contra Costa Health Services for fourteen years. </p>
				<p> As one of the pioneers in understanding social determinants of health, she worked to address the ways in which social and economic disparities and inequities influence birth outcomes and generational health across the life course. The enduring focus of her work was reducing and eliminating health disparities and inequities in birth outcomes through the implementation of the Life Course Perspective.</p>
				<p>Dr. Pies was the recipient of the MCHB Director&rsquo;s Award in 2018.  She also received the APHA MCH Section Award for Leadership &amp; Advocacy.</p>
				<p><a href="cheri-pies.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Terri Powell</button>
			<div class="panel">
				<p><img src="../../images/terri-powell.jpg" alt="Terri Powell" class="right ppic" /></p>
				<p><a href="https://publichealth.jhu.edu/faculty/2547/terrinieka-powell">Terrinieka W. Powell</a>, PhD, is currently (2021) an Associate Professor in the <a href="https://publichealth.jhu.edu/departments/population-family-and-reproductive-health">Department of Population, Family and Reproductive Health</a> at Johns Hopkins Bloomberg School of Public Health is a member of the faculty for Hopkins MCH Center of Excellence. She has an extensive history of using community-engaged approaches and working with community partners (e.g., churches, libraries and youth-oriented CBOs) to conduct research. Her specific expertise is in adolescent health, qualitative methods, intervention development and implementation science. Dr. Powell has collaborated with institutions across several states to promote educational attainment as well as prevent teen pregnancy, HIV, and substance use among adolescents. She has over 40 publications and has been PI or Co-I on 10 externally funded grants that seek to improve the lives of vulnerable young people.</p>
			</div>
			<button class="accordion">William Sappenfield</button>
			<div class="panel">
				<p><img src="../../images/william-sappenfield.png" alt="William Sappenfield" class="right ppic" /></p>
				<p><a href="https://health.usf.edu/publichealth/overviewcoph/faculty/william-sappenfield">William M. Sappenfield</a>, MD, MPH, CPH is currently (2021) Professor and Director of the Chiles Center at the College of Public Health, University of South Florida and a member of the faculty of USF&rsquo;s <a href="https://health.usf.edu/publichealth/mch">Center of Excellence in MCH</a>. He also serves as Director of the Florida Perinatal Quality Collaborative (FPQC), a statewide multi-organizational effort to improve health and health care quality of mothers and infants.&nbsp; As both a pediatrician and an epidemiologist, Dr. Sappenfield has 35 years of experience in epidemiological and public health research, teaching, and practice in maternal and child health at a community, state and national level.</p>
				<p> As a nationally recognized leader in the field of maternal and child health epidemiology, Dr. Sappenfield spent the first 22 years of his career as a CDC medical epidemiologist working on assignment with state and local public health agencies to enhance their capacity to use epidemiology, evaluation and research to improve the health of the women and children.  He completed his CDC career serving four years as Team Leader of the MCH Epidemiology Program directly responsible for the national MCH EPI effort including training, mentoring and supporting maternal and child health epidemiologists around the nation. Upon retiring from the CDC, Dr. Sappenfield served six years at the Florida Department of Health as the State MCH Epidemiologist and as Unit Director for the MCH Practice and Analysis Unit. </p>
				<p>Dr. Sappenfield&rsquo;s other significant maternal and child health contributions include: early developments in the community-based fetal, infant and maternal mortality reviews, adapting an applied approach to investigating a community&rsquo;s infant mortality problem called &ldquo;Perinatal Periods of Risk,&rdquo; developing core state indicators for monitoring preconception health and MCH life course, and promoting best practices in maternal and child health epidemiology.&nbsp; Dr. Sappenfield has received multiple awards including the 2003 National MCH Epidemiology Award for Outstanding Leadership, the 2014 MCH Bureau Director&rsquo;s Award from Health Resources and Services Administration, and the 2016 John C. MacQueen Annual Lectureship Award from the Association of Maternal and Child Health Programs.</p>
			</div>
			<button class="accordion">Ellen Schafer</button>
			<div class="panel">
				<p><img src="../../images/ellen-schafer.jpg" alt="Ellen Schafer" class="right ppic" /></p>
				<p><a href="https://www.boisestate.edu/spph/ellen-schafer/">Ellen Schafer</a>, PhD, MPH, MCHES, is an Assistant Professor in the Department of Public Health and Population Science at Boise State University, Idaho (2018-present). She earned her doctoral degree in Public Health with an emphasis on Community and Behavioral Health from the University of Iowa in 2015 and completed a two-year postdoctoral fellowship in Maternal and Child Health at the University of South Florida (2016-2018) before taking her faculty position at Boise State. She is a Master Certified Health Education Specialist.  Dr. Schafer&rsquo;s main research objective is to understand the mechanisms by which social context and social network influences are associated with health behaviors, and she typically applies these factors to studies of infant feeding and care. </p>
				<p> Dr. Schafer teaches health promotion and education, and public health classes. Her professional health education experience includes a position as a health and wellness specialist working with school districts in New York State to develop, implement, enforce, and evaluate tobacco-free campus policies and educational initiatives K-12. Dr. Schafer also worked at the University of Mississippi as the Assistant Director of Student Health for Health Promotion, where she directed and implemented all health education and promotion activities on campus for students and staff.</p>
			</div>
			<button class="accordion">Donna Strobino</button>
			<div class="panel">
				<p><img src="../../images/Donna-Strobino.jpg" alt="Donna Strobino" class="right ppic" /></p>
				<p><a href="https://publichealth.jhu.edu/faculty/678/donna-strobino">Donna Strobino</a>&nbsp;PhD, is Professor in the Department of Population, Family and Reproductive Health at the Johns Hopkins Bloomberg School of Public Health (JHSPH).  Dr. Strobino has been an anchor for MCH academe at Hopkins for many years.  Most notably, she served as Director of the <a href="https://publichealth.jhu.edu/center-of-excellence-in-maternal-and-child-health">Center of Excellence in MCH</a>, from 2004 to 2020 and of the MCH Epidemiology Doctoral Training Program since 2008. Dr. Strobino has devoted her research career to MCH research with a special focus on the health of disadvantaged women during pregnancy and their young children and families. Her major perinatal health research contributions center on understanding the reasons why disadvantaged women have unfavorable pregnancy outcomes, and interventions to improve their outcomes.</p>
				<p> Dr. Strobino&rsquo;s more recent research addresses maternal mental health as well as the interface of women&rsquo;s chronic conditions and mental and psychosocial health in pregnancy with an eye to reducing neonatal morbidity as well as the burden of disease as women age. She has also studied the impact of maternal depressive symptoms on young children&rsquo;s behavior and growth as well as parenting behaviors and use of preventive health services. Dr. Strobino currently collaborates with students and other faculty on studies of maternal morbidity and its impact on postpartum health, as well as the impact of chronic conditions on morbidity. She has conducted numerous evaluations of perinatal health programs in a variety of settings and pediatric programs for young children. She was Principal Investigator of the National Evaluation of Fetal and Infant Mortality Review Programs and was a key investigator for the national evaluation of the Healthy Steps for Young Children Program. </p>
				<p>Dr. Strobino was honored in 2020 with the National MCH Epidemiology&nbsp;Zena Stein and Mervyn Susser Award for Lifetime Achievement. She also was awarded the highly prestigious 2020 Ernest Lymans Stebbins Medal for her extraordinary contributions to the teaching programs at made at the Johns Hopkins Bloomberg School of Public Health. </p>
				<p><a href="donna-strobino.php">Access the full interview here</a>.</p>
			</div>
			<button class="accordion">Joseph Telfair</button>
			<div class="panel"> <img src="../../images/Joseph-Telfair.jpg" alt="Joseph Telfair" class="right ppic" />
				<p><a href="https://jphcoph.georgiasouthern.edu/">Joseph Telfair</a>, MSW, MPH, DrPH is Professor and Associate Dean of Public Health Research and Practice at the Georgia Southern University College of Public Health (2018-current).  Dr. Telfair is also a member of the graduate faculty at the University of North Carolina at Greensboro Graduate School as well as the Gillings School of Public Health (Chapel Hill), primarily affiliated with the Department of Maternal and Child Health. He has a three-decades long history of experience in a wide range of health care fields, with a substantial focus on MCH, public health practice, evaluation, and cultural and social determinants of health. Notable past positions held by Dr. Telfair include fifteen years with the University of Alabama with faculty appointments in the School of Medicine, the School of Social Work as well as the School of Public Health Department of Maternal and Child Health. He practiced clinical social work for ten years before launching his career in public health.</p>
				<p> Dr. Telfair has served on numerous prestigious panels and advisory boards as an expert based on his recognized scholarship in the areas of sickle cell disease, maternal and child health, and public health research, evaluation and policy. Among the many are Senior Advisor/Consultant for the National Center for Cultural Competence; member of the Secretary&rsquo;s Advisory Committee on Genetics, Health, and Society; Public Health Practice Advisory at the Institute for Child Health Policy, Division of Policy and Programs; and a member of the National Technical Advisory Panel for the Healthy Start Evaluation. Dr. Telfair also is extensively published in the areas of sickle cell disease, maternal and child health, HIV care, evaluation-based research, cultural and ethnic diversity, community-based research, and adolescent health. </p>
				<p>Dr. Telfair has been actively involved in the Association of Teachers of Maternal and Child Health and has held a number of leadership positions in the American Public Health Association, including serving as its President in 2018. </p>
			</div>
			<button class="accordion">Martha Wingate</button>
			<div class="panel">
				<p><img src="../../images/martha-wingate.jpg" alt="Martha Wingate" class="right ppic" /></p>
				<p><a href="https://scholars.uab.edu/display/mslay">Martha S. Wingate</a>, DrPH, MPH, Professor in the Department of Health Care Organization and Policy, served as Director of the HRSA-funded Center of Excellence in MCH, Science, and Practice from 2011 through 2020.  Dr. Wingate continues as Director of the Maternal and Child Health (MCH) Policy and Leadership Concentration and teaches courses in public health systems, maternal and child health, leadership, and perinatal health issues.</p>
				<p> Dr. Wingate&rsquo;s work focuses on preterm birth, fetal and infant mortality, racial and ethnic disparities in birth outcomes, and health policies related to pregnancy and infant health. She is further substantially engaged in providing technical assistance for the MCH workforce at the local, state, and national levels.</p>
				<p>She has published over 50 articles in a number of peer-reviewed journals, including American Journal of Public Health, Social Science and Medicine, and American Journal of Obstetrics and Gynecology and is co-author of a textbook on perinatal epidemiology. She served several terms as President of the Association of Teachers of Public Health.  Included among her many awards is the Loretta P. Lacey Award for MCH Academic Leadership (2012).</p>
			</div>
		</div>

		<button class="accordion"><i class="icon mch-device-desktop" aria-hidden="true"></i> Alternate Access to Interviews</button>
		<div class="panel">
			<p>Interview topics with each of these MCH academics:</p>
			<ul>
				<li><a href="career.php">Career to date and becoming a leader or co-leader of an MCH training program</a>.</li>
				<li><a href="service.php">Involvement with state MCH/Title V programs and other critical MCH Initiatives</a>. </li>
				<li><a href="challenges.php">Challenges and concerns for academics</a>.</li>
				<li><a href="credit.php">Credit for your successes</a>.</li>
				<li><a href="tips.php">Tips for becoming a successful MCH Academic</a>. </li>
				<li><a href="mentoring.php">Thoughts about teaching and mentoring</a>.</li>
				<li><a href="uniquness.php">Unique skills and knowledge needed to lead an MCH Training grant or program</a>.</li>
				<li><a href="strengthen-mch.php">Thoughts about advancing the field of MCH</a>.</li>
			</ul>
		</div>
		<!--<button class="accordion"><i class="icon mch-icon" aria-hidden="true"></i> Credits and Acknowledgments</button>
    <div class="panel">
      <p>This project is led by Dr. Arden Handler (UIC-SPH MCH-CoE) and Holly Grason, MA (JHU MCH-CoE) with assistance from students from various MCH programs. John Richards and his team from the MCH Navigator help to gather, edit, and add the collected &ldquo;stories&rdquo; and related resources to the MCH Navigator, preserving this knowledge for posterity and allowing it to be shared with future MCH academics as well as those considering this career path. </p>
<p>Interviews from Phase 1 of the project were conducted  by Bethany Dominik, MPH, and Cindy San Miguel, MPH, from the University of Chicago School of Public Health Center of Excellence.&nbsp; </p>
      <p>Interviews from Phase 2 of the project were conducted by Kaitlin Bagley, MPH, Public Health Analyst, Division of MCH Workforce Development, HRSA&rsquo;s Maternal and Child Health Bureau.</p>
      <p>Interview from Phase 3 of the project were conducted by Joyce Imafidon and Deborah Ireoluwa Makanjuola from the University of Alabama at Birmingham School of Public Health.</p>
      <p>We wish to acknowledge and extend our gratitude to Meredith Morrissette, MPH, and Michelle Menser Tissue, MPH, at HRSA's Maternal and Child Health Bureau for providing resources, advice, and encouragement through the entire process.</p>
    </div>-->
	</div>
</div>
<?php include('../../incl/footer.html'); ?>
